### ISSUE TITLE
[Question] Could someone please point me to the corresponding maven repository

### ISSUE THREAD

**Issue by krishna-meduri-twi** [microsoft/CDM#103]
Really, appreciate the effort that has been put into this initiative. It's wonderful and got lots of potential to become a silver bullet for metadata management in distributed systems.
Currently, we are trying to use CDM as part of our metadata management initiative. Could someone please point me to the maven repository? 
Thank you.

**Comment by miroslavplese** [comment]
Thanks for your comments. Please note that the CDM SDK is not currently being made available in any public Maven repository. However, we do have tentative plans to publish it to Maven by end of January.

**Comment by miroslavplese** [comment]
CDM SDK is now available on MavenCentral, latest version is [1.0.13](https://search.maven.org/artifact/com.microsoft.commondatamodel/objectmodel/1.0.13/jar).
