### ISSUE TITLE
CDM .9 Null Pointer Exception

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#113]
Hello,
I was running the the following command on Window 10, Maven 3.5, Amazon JDK 11.04 on the .9 release of CDM.  Is there any potential environment factors on my end that could cause this?

Thanks

com.microsoft.commondatamodel.objectmodel.storage.AdlsAdapterTest | computeModifiedDateTest | 1577130666373 | 813
writeAndReadTest | 1577130667195 | 4
--
java.util.concurrent.CompletionException: java.lang.NullPointerException 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)

**Comment by miroslavplese** [comment]
Hello - the library has been built and tested with AdoptOpenJDK. If you can try using that instead of Amazon JDK, it should resolve your issue. Thanks.
