### ISSUE TITLE
CDM and relationship for entities spanning across multiple model.json

### ISSUE THREAD

**Issue by Deepanshu2017** [microsoft/CDM#115]
Hello,

Let's consider this scenario

- Dataflow   -- Dynamics365
- Entity        -- Cases
- attribute   -- ContactId

Second
- Dataflow    -- Website
- Entity         -- WebsiteUsers
- attribute    -- UserId

Above we have 2 dataflows and 2 entities and we have 2 model.json, 1 for each dataflow. Now I have a many to one relationship between `Cases.ContactId` and `WebsiteUsers.UserId` where One `WebsiteUser` can have multiple `Cases`.

How can I specify this kind of relationship in CDM model? Do I need to update both the model.json? If yes, what should be the update? Do I also need to add references? What kind of references do I need to add?

**Comment by llawwaii** [comment]
Hi,

I'm sorry for the late response. Could you please share more details? It would help us better how the scenario is like. (e.g. what do you want to achieve by using CDM?)
