### ISSUE TITLE
Question: Sales part of CDM vs ARTS 

### ISSUE THREAD

**Issue by Tridy** [microsoft/CDM#116]
Hi.

I have a question about the scope of the Sales part of the CDM.

Has this anything to do with ARTS?
https://www.omg.org/retail-depository/arts-odm-73/

both ARTS and CDM are "standards", but there is much more in ARTS around retail

how do I compare these two standards?

Thanks!

**Comment by oovanesy** [comment]
Hello,
Currently published CDM entity definitions reflect Dynamics 365 definitions of entities (including those in sales area). there is no specific link to ARTS. CDM is an extensible metadata definition language and set of standards that can be used to define entities following other commonly used definitions like ARTS. We'd love to see the ecosystem of CDM being used to define entities for other standards
