### ISSUE TITLE
Entity Names in manifest file 

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#117]
Hi,
While streaming my way thru the CDM manifest files, I came across one with entityName's that include the file extension, per below.  In all prior manifest files, the entityNames were name specific.

Is there some reason for this?

Thanks
 
{
    "$schema": "CdmManifest.cdm.json",
    "jsonSchemaSemanticVersion": "0.9.0",
    "imports": [],
    "manifestName": "projectCommon",
    "explanation": "CDM standard entities",
    "entities": [
        {
            "type": "LocalEntity",
            "entityName": "BookableResource.cdm.json",
            "entityPath": "BookableResource.cdm.json/BookableResource"
        },

**Comment by miroslavplese** [comment]
Hi, thanks for reporting this issue. The entityName property should contain just the name of the entity, not the document name. This will be corrected in the next publication of the schema documents.

**Comment by miroslavplese** [comment]
The entity name has been corrected, closing issue.
