### ISSUE TITLE
Question on applicationCommon Activity

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#120]
The Activity.0.9.cdm.json file includes an initial list of members per below that appear to be optional fields as indicated in the CDM browser for activityAdditionalParms as 'additional information provided by external application as json'. 

The browser displays a super set of these values, and appears to utilize a different naming convention.  For example, stripping out 'activity' from the tags provides a 'delivery' label, whereas as the closest label in the browser is 'deliveryLastAttemptedOn'.

Is this approach part of extending the CDM schema and/or are there json file naming or location conventions we should follow?

Is there a sample json file for review that would show the format and required content to provide this information? 

Thanks

"members": ["activityAdditionalParams",
"activityInstanceTypeCode",
"activityIsMAPIPrivate",
"activitySeriesId",
"activityDelivery",
"activityCommunity",
"activityLeftVoiceMail",
"activityExchangeSync",
"activityPostponeProcessingUntil",

**Comment by Venkata1920** [comment]
Hi @cashel1, please look at the "Resolved" tab in the CDM browser (Entity navigator). The list you're looking at was the result of an internal factoring exercise.
