### ISSUE TITLE
example-public-standards is incomplete

### ISSUE THREAD

**Issue by msgerneu** [microsoft/CDM#121]
It looks like that the standards.manifest.cdm.json is not valid because of missing files. 
Concrete, crmCommon.manifest.cdm.json is referencing accelerators not available in the package. e.g. automotive.manifest.cdm.json which is referenced as entity (accelerators.manifest.cdm.json)  and relation (crmCommon.manifest.cdm.json), but not part of the git-package

**Comment by miroslavplese** [comment]
@msgerneu - thanks for reporting this. The schema should be properly structured now, can you please confirm on your end? If not, can you please provide specific line numbers in the schema files where you see these discrepancies?
