### ISSUE TITLE
CDM ADLS storage adapter support sovereign cloud

### ISSUE THREAD

**Issue by catweisun** [microsoft/CDM#135]
The ADLS storage adapter is using the public Azure endpoint for storage and AAD authentication, it doesn't support sovereign cloud environment. 
Suggest to refer [this](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-management/src/main/java/com/azure/core/management/AzureEnvironment.java)  to enable the sovereign cloud adoption in Java/Python/CSharp

**Comment by miroslavplese** [comment]
Hello - we currently don't have plans to introduce sovereign cloud support in ADLS adapter for Common Data Model SDK. If this is a blocker for adopting the SDK in your product, please contact me directly to discuss the options. Thanks.
