### ISSUE TITLE
Nuget/SDK availability

### ISSUE THREAD

**Issue by peterbjorkmarker** [microsoft/CDM#136]
I am writing a custom application that uses the export from PowerApps to Azure Data Lake gen2 as a data source. Instead on relying on the Azure.Storage.Files.DataLake nuget package I would like to use the ADLS adapter as outlined here https://docs.microsoft.com/en-us/common-data-model/0.9om/api-reference/storage/adlsadapter. 

I am unable to find any published nuget packages for this on nuget.com. Do I need to fork the code from this repo? How am I expected to use it?

**Comment by mfriscia7** [comment]
The ADLS adapter is there to provide a way for the sdk to pull ADLS data, it is not meant to be a stand alone package to work with ADLS so there will not be a nuget package for this.
