### ISSUE TITLE
Load schema locally do not display attributes

### ISSUE THREAD

**Issue by mariotoffia** [Microsoft/CDM#14]
Steps to reproduce:
1) Clone CDM git repo.
2) Click on CDM\docs\experimental\index.html
3) Click on Load from files... button and select the CDM\schemaDocuments folder

The left pane is populated with the classes but is not populated the same way as the "load from GitHub!" button. The left pane do not show any attributes or other schema information.

**Comment by JeffBern** [comment]
the 'experimental' browser works with the documents that are in the experimental branch. because gh pages can't work with branches, we needed to host the browser in the master branch of docs. Did you clone the experimental branch?

**Comment by mariotoffia** [comment]
@JeffBern My mistake - sorry. I did not check for a experimental branch instead just used the experimental forlder in the master branch!

Thanks! :)
