### ISSUE TITLE
Read abstract manifest with submanifest and generate resolved manifest with submanifest

### ISSUE THREAD

**Issue by Akkilz** [microsoft/CDM#140]
I am trying to read abstract parent manifest file with two submanifest and generating resolved manifest with submanifest.

I have seen example, one manifest with entites and not with nested manifest.

```
var cdmCorpus = new CdmCorpusDefinition();
string pathFromExeToExampleRoot = "../../../../../../";
cdmCorpus.Storage.Mount("local", new LocalAdapter(pathFromExeToExampleRoot + "2-create-manifest"));

cdmCorpus.Storage.DefaultNamespace = "local"; 
cdmCorpus.Storage.Mount("cdm", new LocalAdapter(pathFromExeToExampleRoot + "example-public-standards"));

var manifest = await cdmCorpus.FetchObjectAsync<CdmManifestDefinition>("local:/mainAbstract.manifest.cdm.json");

var manifestResolved = await manifest.CreateResolvedManifestAsync("local:/digitalTwin", "local:/resolved/{n}.cdm.json");
manifestResolved.Imports.Add("cdm:/foundations.cdm.json");

await manifestResolved.SaveAsAsync($"{manifestResolved.ManifestName}.manifest.cdm.json", true);
await manifestResolved.SaveAsAsync("model.json", true);
```

I have mannually created manifest with submanifest and used entity navigator its resolving as expected but not able to do with c# sdk.

Sample used : This zip file has parent manifest and two sub manifest with respective directory.
[parentWithSubManifest.zip](https://github.com/microsoft/CDM/files/4345761/parentWithSubManifest.zip)

Main abstract manifest
```
{
  "$schema": "mainclickstream.cdm.json",
  "jsonSchemaSemanticVersion": "1.0.0",
  "imports": [
    {
      "corpusPath": "cdm:/foundations.cdm.json"
    }
  ],
  "manifestName": "mainclickstream",
  "explanation": "CDM standard entities",

  "subManifests": [
    {
      "manifestName": "site",
      "definition": "site/site.manifest.cdm.json"
    },
    {
      "manifestName": "building",
      "definition": "building/building.manifest.cdm.json"
    }
  ]
}
```

If any sample or guidence is really helpful.

**Comment by mfriscia7** [comment]
Seeing your more recent question, I'm guessing this is resolved?

**Comment by Akkilz** [comment]
Thanks for your respone. I have closed that issue. This one is little different.
reading abstarct manifest which has submanifest and generate resolved manifest.
Thing is its not generating resolved manifest properly, need sample or guidence how to for nested manifest.

**Comment by perdasilva** [comment]
I'm having a similar problem. I have a root manifest which defines no entities, only a sub manifest.
When resolving the top level manifest, the resolved manifest has no entities (or even a sub manifest).

```
{
  "jsonSchemaSemanticVersion": "1.1.0",
  "$schema": "CdmManifest.cdm.json",
  "documentVersion": "2.0",
  "manifestName": "testManifest",
  "explanation": "testManifest",
  "subManifests": [
    {
      "manifestName": "sub",
      "definition": "sub/sub.manifest.cdm.json"
    }
  ]
}
```

When trying to resolve:

```
const manifest = await this.cdmCorpus.fetchObjectAsync<CdmManifestDefinition>('local:/testManifest.cdm.json')
const resolvedManifest = await manifest.createResolvedManifestAsync("local:/resolved", 'local:/resolved/{n}.cdm.json')
```

any ideas what I'm doing wrong?
