### ISSUE TITLE
CDM Changes from .9 to 1.0

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#142]
Hello,
I was reviewing the changes in the latest release and cannot locate the .9 files including CdsStandard, ActivityCommon and ActivitySystem which were located in the core folder in the .9 version.
The advanced CDM navigator still shows these base classes.  Is this meta data accessed in some other fashion?

Thanks

**Comment by SukanyaSrinivasan** [comment]
Hi,

Thank you for your note.

Currently, the CDM navigator only allows loading the default version (which is currently 1.0) from github. You can locally download the schema documents from the public github location and use the 'load from file' feature of the navigator to view the older 0.9 versioned schema and manifest.

We have taken your feedback. In the future, we will plan for a feature in the Navigator that allows loading and displaying older versions of the schema directly from github.

Thanks,
CDM Team
