### ISSUE TITLE
Minor Version Issue

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#143]
Thanks for the followup on my last issue.

Noticed that the LinkedInLeads.manifest.cdm.json and the marketing manifest file list the current version as .09.  This is in both the 1.0 version of the manifest file and the manifest file that is not versioned. 

Also, what is the purpose of the non-versioned file ? Appears to always be close the the last version of the manifest.

Thanks

**Comment by SukanyaSrinivasan** [comment]
Thank you for bringing this to our notice.
We will confirm if this entity and manifest is expected to have a 1.0 version and update the schema if required.
Thanks,
CDM Team
