### ISSUE TITLE
partnership

### ISSUE THREAD

**Issue by momohuri** [microsoft/CDM#145]
Hi, 
I work at a data company named LoreIO (https://www.getlore.io/).
We are currently looking at the CDM and how to integrate it into our product to help our customers map their raw data to the CDM. 
I was wondering who should we contact to talk about a partnership. Mainly because we would like to extend the CDM for new industries.
But also talk about how we could integrate the CDM and CDS inside our product which is not part of the microsoft ecosystem.

Thanks!

**Comment by SukanyaSrinivasan** [comment]
Please reach out to [CDM Partner Support](mailto:cdm-partner-support@microsoft.com) and provide details of your scenario.
