### ISSUE TITLE
Issue about saving DataFormat Int64 and Int16

### ISSUE THREAD

**Issue by wheatdog** [microsoft/CDM#147]
I encounter some issues about integer DataFormat while converting model.json to *.manifest.cdm.json. Inside <entity>.cdm.json, I found the DataFormat of an attribute got silently converted to Int32 from Int64.

After digging into code, I think that might be a bug and #146 is a quick patch.

**Comment by SukanyaSrinivasan** [comment]
Thank you for your note. We have opened an bug to investigate this further.

**Comment by mfriscia7** [comment]
Thank you for bringing this up, this issue that has already been brought to our attention. A fix for it will be out on our next release which you should be out by the end of next week.
