### ISSUE TITLE
Manifest Version Id in 1.1 Version

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#148]
Hi,
Noticed the manifest files for LinkedInLeads, Marketing and CustomerInsights are referencing the .9 version.  The manifest file names and the schema files correctly indicate 1.0.

Ran thru all of the modules so this should close out the list.

Thanks

**Comment by SukanyaSrinivasan** [comment]
Thank you for your note. We have opened an bug to investigate this further.

**Comment by jinichu** [comment]
These manifest files have been fixed as of commit [1bd730febfba14114849890aa033faf62d7a0cce ](https://github.com/microsoft/CDM/commit/1bd730febfba14114849890aa033faf62d7a0cce)
