### ISSUE TITLE
Broken URL for Open Data Initiative

### ISSUE THREAD

**Issue by itsnotaboutthecell** [microsoft/CDM#149]
URL: https://github.com/microsoft/CDM
Issue: The link within the following sentence for "Open Data Initiative" is broken.
"As announced at Microsoft Ignite, the Common Data Model is evolving as part of the Open Data Initiative, a jointly-developed vision by Microsoft, Adobe, and SAP."

Broken URL: https://www.microsoft.com/en-us/quantum/open-data-initiative
Should be updated to: https://www.microsoft.com/en-us/open-data-initiative

**Comment by dingbx** [comment]
Thanks for pointing it out. It's updated now.
