### ISSUE TITLE
Tokenprovider constructor of AdlsAdapter does not set HttpClient causing NullReferenceException

### ISSUE THREAD

**Issue by marcschier** [microsoft/CDM#151]
https://github.com/microsoft/CDM/blob/949ec6347b491491c1da8453bd4d84e92425ad28/objectModel/CSharp/Microsoft.CommonDataModel.ObjectModel.Adapter.Adls/Storage/ADLSAdapter.cs#L169

Should call : this() to initialize client.

**Comment by jinichu** [comment]
Thank you for bringing this up. We have opened a ticket to track this issue.

**Comment by jinichu** [comment]
We have fixed this bug. It will be added as part of our next release, which will be happening within the next couple of weeks.
