### ISSUE TITLE
Combine sources with seperate CDM model.json

### ISSUE THREAD

**Issue by datasharkNL** [microsoft/CDM#157]
Hi all,

Is it possible to combine different sources? So, for example, that Power BI writes its data flows to a CDM folder with model.json and Dynamics writes its entities with model.json.

How can I combine these 2? So as an example:
Combine Account from Power BI and from Dynamics, so that I have one time Account in my reporting from two different sources. And that the model.json is correct.

See the image from the Microsoft site with examples of multiple sources (Power BI & Dynamics etc)
![image](https://user-images.githubusercontent.com/54980443/84171618-50b59c00-aa7b-11ea-927c-371c445af6d6.png)

**Comment by olegovanesyan** [comment]
Hello,
Common Data Model is not a data service/query engine and it can't be used to create a "union" or "join" of actual data. The diagram above illustrates the CDM file organization. I suggest you try using CDM feature of public preview of Power BI connector for ADLSg2 https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-april-2020-feature-summary/ - scroll down to "CDM Folder view for Azure Data Lake Storage Gen2". It would let you bring data into Power BI for further processing.

**Comment by datasharkNL** [comment]
> Hello,
> Common Data Model is not a data service/query engine and it can't be used to create a "union" or "join" of actual data. The diagram above illustrates the CDM file organization. I suggest you try using CDM feature of public preview of Power BI connector for ADLSg2 https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-april-2020-feature-summary/ - scroll down to "CDM Folder view for Azure Data Lake Storage Gen2". It would let you bring data into Power BI for further processing.

So to combine these you need a tool like these to combine these sets from different systems:

-  ADF (Mapping Data Flow) - New feature: https://techcommunity.microsoft.com/t5/azure-data-factory/adf-adds-support-for-inline-datasets-and-common-data-model-to/ba-p/1441798

- Databricks (https://github.com/Azure/spark-cdm-connector)

However, the spark library cannot yet write a model.json. "Supports writing to CDM folders described by a manifest file only. Write support for model.json file is not planned."

For example the new provided functions for Dynamics 365 (Entity Stores to Data Lake and the coming feature Tables to Data Lake) generate model.json files instead of the other model files.

**Comment by olegovanesyan** [comment]
Hi datasharkNL, following up on this thread - is there any specific info you are looking for?
Thanks
