### ISSUE TITLE
PiPY cdm module

### ISSUE THREAD

**Issue by momohuri** [microsoft/CDM#158]
Hi, 
I have been using the python SDK for some project. For this, it would be more convenient to have a package in PiPY 
I believe that there is only two things that would need to be changed : 
 - update the URL in setup.py
 - modify the copy command to fetch the schema files online instead of requiring to have the CDM project cloned. 
 
Let me know if it is something that you are planning to do. 

thanks

**Comment by mfriscia7** [comment]
Hello,
We want to make the python SDK available through PiPY in the future, but we do not currently have plans to do it now.
