### ISSUE TITLE
Versioning and labeling

### ISSUE THREAD

**Issue by mariotoffia** [Microsoft/CDM#16]
Hi, I'm wondering if it is possible for you to label with a version that is the current release in the PowerApps based CDS so we can detect in our buildflow changes directly from git?

Cheers,
 Mario

**Comment by theresapalmer** [comment]
Hi Mario - just to better understand, is your request to maintain the solution/schema versions that show up in CDS in these CDM definitions? Currently there isn't a single version of CDS that these schemas match to, as each piece of the schema (the entities, attributes etc.) can be extended or modified by multiple solutions (Sales, Service, Industries accelerators etc.) each with their own version. Maintaining a full map would be quite complex but if I can better understand your scenario we might have other options.

**Comment by mariotoffia** [comment]
@theresapalmer I thought you had a "overarching" version such as history of: https://github.com/Microsoft/CDM/commits/master/schemaDocuments/schema.cdm.json

that would be provisioned onto the CDS in order to have some form of schema sync between this repo and the CSD.

Since it is not the case, you can close this issue :)

Cheers,
 Mario
