### ISSUE TITLE
Entity Relationship Diagram

### ISSUE THREAD

**Issue by fyuuhi** [microsoft/CDM#161]
Hi Team,

Is it possible to get an Entity Relationship Diagram for Common Data Model?
If yes, please let me know how to get diagrams.

Best regards,

**Comment by SukanyaSrinivasan** [comment]
Hi,

Can you please provide more details on what you are trying to do?

1) If it is to view and explore the CDM standardized entities metadata you can go to  - https://microsoft.github.io/CDM/ and use the Entity Navigator.

2) If it is to view a CDM model as a ER Diagram stay tuned for https://docs.microsoft.com/en-us/power-platform-release-plan/2020wave1/cdm-data-integration/common-data-model-visualization-management-experience

3) If it is to have a  ERD style design experience – currently we no plans yet.

Hope this helps.

**Comment by fyuuhi** [comment]
HI Sukanya,

Thank you.

My scenario is to view relationships between all of each entity as diagrams (like AX2012 ER diagram,  https://alexdmeyer.com/ax2012erd/Erd-One-AcctPay-AP1-VendTrans.htm) and understand the connections between them.


> If it is to view and explore the CDM standardized entities metadata you can go to - https://microsoft.github.io/CDM/ and use the Entity Navigator.
I browsed the Entity Navigator (https://microsoft.github.io/CDM/), but I wanted to get an easier way to see relationships between entities, like Entity Relationship Diagrams.

> If it is to view a CDM model as a ER Diagram stay tuned for https://docs.microsoft.com/en-us/power-platform-release-plan/2020wave1/cdm-data-integration/common-data-model-visualization-management-experience
I didn't know that. Is that a comprehensive Entity Relationship Diagrams including taxall the entities?
Could you please let me know more information or where to find details about it?

Your reply is really helpful.
Best regards,

**Comment by fyuuhi** [comment]
Hi Sukanya,

Please give me any inputs?

**Comment by SukanyaSrinivasan** [comment]
Hi Yuhi,

Currently there is no comprehensive way to view the complete ER diagram of the entire CDM standardized metadata since it is a very large collection. Hope this answers your question.

Regards

**Comment by fyuuhi** [comment]
Hi Sukanya

Thanks for the kind reply.
It's very helpful.
I understand there is no way to do that.
I  am going to look for the other way.

Best regards,
Yuhi

**Comment by fyuuhi** [comment]
By the way, please consider publishing ER diagram in the future.
Best regards,
Yuhi

**Comment by Universezero** [comment]
Hi @sukanyamsft,
I am also interested in generating an ERD of the CDM - would it be possible to do this for only a small section of the CDM, e.g. Vendor? I have been trying to figure out how to do this using Dataverse / XrmToolBox but have had no success thus far.

**Comment by sing-ideas** [comment]
https://jonasr.app/uml/

Can this tool be used to generate ER Diagram or is it not possible?
