### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/CDM#170]
https://github.com/microsoft/CDM/blob/1027feab9c2361802e860b1f7fb45dc98786ec9f/objectModel/Java/objectmodel/src/main/java/com/microsoft/commondatamodel/objectmodel/cdm/CdmCorpusDefinition.java#L57

https://github.com/microsoft/CDM/blob/1027feab9c2361802e860b1f7fb45dc98786ec9f/objectModel/Java/objectmodel/src/main/java/com/microsoft/commondatamodel/objectmodel/cdm/CdmCorpusDefinition.java#L60
This field is never used

**Comment by SukanyaSrinivasan** [comment]
Hi,
Thank you for the feedback!
