### ISSUE TITLE
schedulingEngine field duplication across inherited classes

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#171]
The schedulingEngine field appears in both the foundationCommon.Organization and scheduling.Organization classes.  

As the scheduling.Organization extends the base_Organization, I'm getting a duplicate field error as I'm resolving 'base-' class extension references in the schema file via the corpusPath (below). 

Is this the correct approach?

Thanks

allImports.1.0 File
     "corpusPath": "/core/applicationCommon/foundationCommon/Organization.1.0.cdm.json",
            "moniker": "base_Organization"

Schema File
"definitions": [
    {
      "entityName": "Organization",
      "extendsEntity": "base_Organization/Organization",
      "exhibitsTraits": [
        {
          "traitReference": "is.CDM.entityVersion",
          "arguments": [
            {
              "name": "versionNumber",
              "value": "1.0"
            }
          ]
        }
      ],

**Comment by dingbx** [comment]
Hi cashel1,

Sorry for the late reply. 
It looks like you are extending the foundationCommon.Organization and it shouldn't have conflicts with scheduling.Organization. Can you specify what you are trying to do? I also tried resolving scheduling.Organization and it didn't report any error.

Thanks,
Yijing

**Comment by cashel1** [comment]
Hello Yijing, thanks for getting back.  

The schedulingEngine field appears in two separate schema files (foundationCommon.Organization.cdm.json and foundationCommon.crmCommon.projectCommon.scheduling.Organization.cdm.json.  

The _allImports.1.0.cdm.json file inside the scheduling folder lists this:
 {
            "corpusPath": "/core/applicationCommon/foundationCommon/Organization.1.0.cdm.json",
            "moniker": "base_Organization"
        },
as in import, which is how I'm determining inheritance.

Thanks

**Comment by llawwaii** [comment]
Hi,

Sorry for the late response. `_allImports.1.0.cdm.json` is not the latest version of the schema. The non-versioned schema files are the latest files, I think you would want to refer to this 
[_allImports.cdm.json[(https://github.com/microsoft/CDM/blob/master/schemaDocuments/core/applicationCommon/foundationCommon/_allImports.cdm.json).

Let me know if you have more questions.

Thanks

**Comment by mfriscia7** [comment]
Hello,

When fetching the scheduling/Organization entity, the object model should overwrite the schedulingEngine attribute from base_Organization with the schedulingEngine attribute that is found in scheduling/Organization. If this is still an issue can you attach the error that you are seeing?

**Comment by miroslavplese** [comment]
Hi,

We will close the issue due to lack of response. In case you still have this problem, please reopen the issue. Thanks.
