### ISSUE TITLE
I want to read files from the local window system, such as disk D. how can I change this front page

### ISSUE THREAD

**Issue by chenk3299** [microsoft/CDM#178]
I want to read the JSON files from the local window system, such as disk D. how can I change this front page.

**Comment by mfriscia7** [comment]
Hi, if you want to use a local version of our JSON schema files you can setup a local adapter pointing to the path where you have put the files:

`
var corpus = new CdmCorpusDefinition();
corpus.Storage.Mount('cdm', new LocalAdapter('D:/path/to/files');
`

Overriding the default 'cdm' adapter will tell the object model to use your local files instead.

**Comment by chenk3299** [comment]
> Hi, if you want to use a local version of our JSON schema files you can setup a [local adapter](https://docs.microsoft.com/en-us/common-data-model/1.0om/api-reference/storage/localadapter) pointing to the path where you have put the files:
> 
> ```
> var corpus = new CdmCorpusDefinition();
> corpus.Storage.Mount('cdm', new LocalAdapter('D:/path/to/files');
> ```
> 
> Overriding the default 'cdm' adapter will tell the object model to use your local files instead.

thank you
