### ISSUE TITLE
Is Parquet supported now?

### ISSUE THREAD

**Issue by peizhou298** [microsoft/CDM#179]
We saw "is.partition.format.parquet" in some settings but found in some doc said CDM only support CSV so far, so we want to know is parquet officially supported now?

**Comment by SukanyaSrinivasan** [comment]
Hi,
Thank you for your question. It is not yet supported publicly. There is a partial (and limited) internal support for it. There are plans to support it eventually, but currently we have no eta / timelines to share for it yet.
