### ISSUE TITLE
Using the python SDK in an azure function

### ISSUE THREAD

**Issue by Sandy247** [microsoft/CDM#180]
What is the recommended way of using the Python SDK in a linux based azure function? I could not find a pypi library. If there exists one, could anyone point me to that? If there isn't one, do you have plans to publish it soon(a timeline?). Or should I just create a function and copy all the necessary resources as documented in the [README](https://github.com/microsoft/CDM/blob/master/objectModel/Python/README.md)? Appreciate your help!

**Comment by TissonMathew** [comment]
@Sandy247 can you publish the method you used? This will help others who are using the SDK.

**Comment by miroslavplese** [comment]
@Sandy247 - we don't have a PyPI package available yet, but it is in our roadmap. Right now work is underway to make the SDK available in Nuget (for .Net) and after that we will start looking into publishing to PyPI. We will let you know once it is available.

**Comment by Sandy247** [comment]
Thanks @miroslavplese! Appreciate the update and great to hear that the pypi library will be out in the near future. Keep me posted.

**Comment by miroslavplese** [comment]
@Sandy247 - the Python SDK v1.0.15 has been released on PyPI. Please look for commondatamodel-objectmodel in the index.
