### ISSUE TITLE
Adding doNotSell to CustomerProfile standard schema

### ISSUE THREAD

**Issue by TissonMathew** [microsoft/CDM#182]
We are a data privacy SaaS platform built on CDM. We would like to add data privacy compliance attributes and traits to CDM. One example is adding a doNotSell flag. What's the best way to handle this so we don't need to branch off from the spec. 

https://docs.microsoft.com/en-us/common-data-model/schema/core/applicationcommon/foundationcommon/crmcommon/solutions/customerinsights/customerprofile

**Comment by olegovanesyan** [comment]
Hi TissonMatthew,
Thank you for the interest in CDM! Question: what would be the intended result of annotating the entity with this signal?

**Comment by TissonMathew** [comment]
We want to push the doNotSell status to AdTech like FB.

**Comment by mukeshpo** [comment]
good suggestion @TissonMathew, you could add it as a separate custom attribute as this does not seem to be available.   Is the intent to do not sell or do not share with any other 3rd party?

**Comment by TissonMathew** [comment]
That's correct. We implemented it as "doNotSell" and rolled out a limited release to our clients,  @sandy247 can update the schema in the github.
