### ISSUE TITLE
Any plans to port the CDM c# SDK to .NET Core?

### ISSUE THREAD

**Issue by TissonMathew** [microsoft/CDM#183]
https://github.com/microsoft/CDM/tree/master/objectModel/CSharp

**Comment by skywalker-wu** [comment]
+1

**Comment by miroslavplese** [comment]
Hello, thanks for asking - we currently do not have plans to port the C# SDK to .NET Core in the next 6 months. We will re-evaluate this requirement again early next year based on customer demand, so it would be good to hear from you why you require it?

**Comment by TissonMathew** [comment]
Our application is .net core 3.1. What’s the best way to use the SDK in a .core app?

**Comment by miroslavplese** [comment]
Our SDK targets netstandard2.0 in addition to net45 and net462. Can you reference SDK's netstandard2.0 assemblies from your app?

**Comment by TissonMathew** [comment]
netstandard2.1 supported? .net 3.0 is what we are using.

**Comment by TissonMathew** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by victor-gutemberg** [comment]
Hey Tisson,

According to the [.NET standard documentation](https://dotnet.microsoft.com/platform/dotnet-standard), .NET core 3.1 supports the standard version 2.0.
We have an internal project that targets .NET core 3.1 and we haven't seem issues building both projects together.

Can you please clarify what kind of issue you are having?

**Comment by dingbx** [comment]
Closing this issue since lack of response, please reopen it if further discussion is needed.
