### ISSUE TITLE
 CdmCorpusDefinition | Document not index previsouly. Please when calling fetchObjectAsync specify the 'importsLoadStrategy' to 'load' on the ResolveOptions object.

### ISSUE THREAD

**Issue by gauthammekala** [microsoft/CDM#185]
Hi,
Many Thanks for ( Microsoft CDM Release Version Update: 1.0.12) Update it has resolved most of the issues 

I have a small confusion on this issue Can you please help me with this (what this error about ?) 

I'm doing this step (abstract to resolved )
```
  const manifest = await cdmCorpus.fetchObjectAsync<
  CdmManifestDefinition
  >("abstract/digitalTwin/digitalTwin.manifest.cdm.json");
   const resolvedManifest: CdmManifestDefinition = await manifest.createResolvedManifestAsync('resolved', undefined);
   await resolvedManifest.saveAsAsync(resolvedManifest.manifestName + ".manifest.cdm.json", true);
```

![image](https://user-images.githubusercontent.com/70132800/94554181-fcb50a00-0259-11eb-9f79-f26a8922ab6e.png)

**Comment by victor-gutemberg** [comment]
Hello,

Sorry to hear that the new update is causing you trouble.

We've introduced in this release a way for users to choose when the imports of a document are loaded. This option can be specified by passing a `resolveOptions` to `fetchObjectAsync`. In the `resolveOptions` you should be able to set the property `importsLoadStrategy` which by default is `lazyLoad`.

What you described looks initially as a bug so I'll do some investigation about it. In the meantime you can set the `importsLoadStrategy` to `load` so all the imports are loaded on `fetchObjectAsync`. After this is fixed you may want to remove this and let the lazy loading do the work for you.

```
const resOpt = new resolveOptions();
resOpt.importsLoadStrategy = importsLoadStrategy.load;
const manifest = await cdmCorpus.fetchObjectAsync<CdmManifestDefinition>("abstract/digitalTwin/digitalTwin.manifest.cdm.json", null, resOpt);
```

**Comment by gauthammekala** [comment]
Hi,

i have add importsLoadStrategy But still error is same ( but seems functionality is working as expected creating ResolvedManifest files )
const resOpt = new resolveOptions();
  resOpt.importsLoadStrategy = importsLoadStrategy.load;

**Comment by XTJX21X** [comment]
- [event log kuberbites type_view_accseibility_type_anouncment_type_touch_explortation_type_text_selection_changed
Type_viewed_focus_it_cleared

**Comment by victor-gutemberg** [comment]
Hi, 

This error was being mistakenly logged and doesn't affect the functionality of the SDK.
It has been already fixed and should be available in our next release. You won't need to specify the imports strategy property anymore.

Thanks for reporting it.

**Comment by dingbx** [comment]
Closing this issue since the new release with the fix is coming in 5 days. Please reactivate if further discussion is needed.
