### ISSUE TITLE
Invalid pom.xml of the Java objectmodel

### ISSUE THREAD

**Issue by cturla** [microsoft/CDM#186]
This pom (https://github.com/microsoft/CDM/blob/master/objectModel/Java/pom.xml) has 2 **\<profiles\>** tags, line 40 and 189. Which would result with the following error if you try to build it:

> Non-parseable POM /Users/charles.turla/git/toro-cdm/objectModel/Java/pom.xml: Duplicated tag: 'profiles' (position: START_TAG seen ...</build>\n\n    <profiles>... @189:15)  @ line 189, column 15

**Comment by jinichu** [comment]
Thank you for bringing this up. I have opened a ticket for this to be addressed soon. I'll keep you updated.

**Comment by dingbx** [comment]
Hi cturla,

This issue is fixed and the new release to GitHub with the fix is coming in 5 days.
