### ISSUE TITLE
Getting start with Python SDK

### ISSUE THREAD

**Issue by jayrumi** [microsoft/CDM#188]
Hi,

Could someone explain how to work with Python SDK. I went through install guide (with some troubles) but now I can't understand how to use this sdk. It also would be great if somebody add information in readme file.

**Comment by llawwaii** [comment]
Hi,

We have some samples that cover a few simple scenarios, you can find them from this [sample](https://github.com/microsoft/CDM/tree/master/samples) folder. 

Please let us know if you need more help. Thank you
