### ISSUE TITLE
Multi-attribute relationships

### ISSUE THREAD

**Issue by InitionsJulius** [microsoft/CDM#192]
**Problem:**
We are extracting SAP data and saving this in a CDM structure on an Azure Data Lake Gen 2. Currently, only single attribute relationships are supported for the CDM ([link](https://docs.microsoft.com/en-us/common-data-model/sdk/manifest)). We are facing the challenge that primary keys in SAP entities are usually a combination of more than one column. Thus, one of the advantages of using CDM structure cannot be used. 

**Question:**
When will it be possible to add this feature of using multi-attribute relationships in a CDM?

**Comment by dingbx** [comment]
Multi-attribute is actually a feature we are working on right now and it will be available early next year. We will update the public docs once the feature released. Please stay tuned! Thanks.
