### ISSUE TITLE
Single-attribute relationships not working

### ISSUE THREAD

**Issue by InitionsJulius** [microsoft/CDM#193]
**Problem:**
We currently verify our CDM structure by importing it to Power BI. The single-attributte relationships ([link](https://docs.microsoft.com/en-us/common-data-model/sdk/manifest)) of the CDM are not detected by Power BI (Sep 2020 version). This could be an error on the side of PowerBI or on the side of the CDM.

**Question:**
Is this a CDM problem or a Power BI problem? How is it possible to test a CDM structure, specifically the relationships, other than by importing with Power BI?

**Comment by olegovanesyan** [comment]
Hello and thank you for reaching out. Q: does the "import to Power BI" mean that you are creating a data flow our using Power BI connector for the lake that can read CDM folders in the lake?

**Comment by InitionsJulius** [comment]
I am using the Power BI connector for the data lake. 
In Power BI: Get data | Azure Data Lake Storage Gen 2 | CDM Folder View

**Comment by mlarryc** [comment]
The support for the relationship of the CDM structure hasn't been added by the ADLS gen2 CDM connector yet. We do have a plan to add this feature in the future, but there's no ETA for it yet.
