### ISSUE TITLE
read-manifest Sample is broken and StorageAdapter class obsolete

### ISSUE THREAD

**Issue by seanmcne** [microsoft/CDM#200]
Cloning & building for the read-manifest solution fails due to missing system dependencies in read-manifest. 

Second, i noticed the sample code is incorrect as AdlsStorage adapter doesn't exist - can someone please update this sample to function such that we can read from ADLS? 
![image](https://user-images.githubusercontent.com/2292260/99444672-2695bf00-28e2-11eb-9c27-c9e105e9021c.png)

Third, when investigating where that went, I noticed our usage of StorageAdapter which is deprecated: 
![image](https://user-images.githubusercontent.com/2292260/99443657-b9355e80-28e0-11eb-8559-52e6570c1287.png)

**Comment by dingbx** [comment]
Hi seanmcne,

Closing this issue since I think this issue is replied via email. Please reactivate if necessary.

**Comment by dingbx** [comment]
For others that coming into this thread with the same question, currently the adls project reference needs to be added into the sample project manually if the ADLSAdapter is used. We will add the references into the samples soon.
