### ISSUE TITLE
Modifying CDM Power BI Dataflow

### ISSUE THREAD

**Issue by Browzer** [microsoft/CDM#201]
Hi,

I have a sample Power BI Dataflow model.json file in which I manipulate the "location" setting, so that I can use the sample file for several clients with a different tenant.

I would like to pass an extra parameter to the Partitions section of the CDM file, so that I can define the delimiter of the file on the location, as this is not always ",". I found out that I should be able to do so, by adding an extra fileFormatSettings clause to the partitions section, beneath "location". Now when I open Power BI, I keep getting an error. Does anyone have an example where they managed to do this for a power bi cdm folder? Or can somebody assist on this topic?

**Comment by dingbx** [comment]
Hi Browzer, 

Sorry for the late response. It seems that what you've done is correct. Can you provide the error that you are getting from PBI and maybe also the manifest.cdm.json file snippet where you added the fileFormatSettings?
