### ISSUE TITLE
ADLSAdapter resiliency enhancement 

### ISSUE THREAD

**Issue by seanmcne** [microsoft/CDM#202]
Would it be possible to make ADLSAdapter more flexible/resilient and allow for the storage account url/input to include https? 

**Broken:** 
var adlsAdapter = new ADLSAdapter("https://mysuperstorage.dfs.core.usgovcloudapi.net", "/commondataservice-orgclone", key);

This would result in a url of: https://https//mysuperstorage.dfs.core.usgovcloudapi.net/commondataservice-orgclone

**Works:** 
var adlsAdapter = new ADLSAdapter("mysuperstorage.dfs.core.usgovcloudapi.net", "/commondataservice-orgclone", key);

This results in the correct url of: https://mysuperstorage.dfs.core.usgovcloudapi.net/commondataservice-orgclone

**Comment by Venkata1920** [comment]
Hi @seanmcne , thanks for the suggestion! As a follow up of our email conversation, this is part of our engineering backlog now.

**Comment by llawwaii** [comment]
@seanmcne,
ADLSAdapter now allows hostname value to start with "https://". it's available in SDK version >= 1.4.0. Let me know if you have more questions. Thanks!
