### ISSUE TITLE
Errors during work with RemoteAdapter 

### ISSUE THREAD

**Issue by jayrumi** [microsoft/CDM#203]
Hi,

I want to tune RemoteAdapter for work with https://cdm-schema.microsoft.com/.

This is a part of my code.

```
async def main():
    cdm_corpus = CdmCorpusDefinition()
    cdm_corpus.ctx.report_at_level = CdmStatusLevel.ERROR

    print('Configure storage adapters')
    cdm_corpus.storage.mount('local', LocalAdapter(root=os.path.join(ROOT_PATH, '../contact-tables')))
    cdm_corpus.storage.default_namespace = 'local'

    adapter = RemoteAdapter(hosts={'cdm-schema.microsoft.com': 'https://cdm-schema.microsoft.com/logical'})
    adapter.number_of_retries = 0
    adapter.timeout = 1000

    cdm_corpus.storage.mount('remote', adapter)

    manifest_abstract = cdm_corpus.make_object(CdmObjectType.MANIFEST_DEF, 'temp_abstract')

    manifest_abstract.entities.append('Account', 'remote:/cdm-schema.microsoft.com/logical/core/applicationCommon/Account.cdm.json/Account')
    
    local_root = cdm_corpus.storage.fetch_root_folder('local')
    local_root.documents.append(manifest_abstract)
    manifest_resolved = await manifest_abstract.create_resolved_manifest_async('default', '')
```

During code execution I get the next errors:

> 2020-11-27 16:42:06,857	ERROR	logger.py:47	_log	2020/11/27 13:42:06,8579 | PersistenceLayer | Could not read /core/wellKnownCDSAttributeGroups.cdm.json from the 'remote' namespace.
>  Reason: Host ID not identified by remote adapter. Make sure to use create_corpus_path to get the corpus path. | _load_document_from_path_async
> 2020-11-27 16:42:08,317	ERROR	logger.py:47	_log	2020/11/27 13:42:08,3175 | PersistenceLayer | Could not read /core/cdsConcepts.cdm.json from the 'remote' namespace.
>  Reason: Host ID not identified by remote adapter. Make sure to use create_corpus_path to get the corpus path. | _load_document_from_path_async
> 2020-11-27 16:42:43,047	ERROR	logger.py:47	_log	2020/11/27 13:42:43,0471 | CdmCorpusDefinition | Unable to resolve the reference 'localizedTable' to a known object | /cdm-schema.microsoft.com/logical/core/applicationCommon/Contact/hasAttributes/attributesAddedAtThisScope/members/externalUserIdentifier/appliedTraits/is.localized.describedAs/arguments/a0/value/ConstantlocalizedTable/entityShape/localizedTable/(ref)
> 2020-11-27 16:42:43,047	ERROR	logger.py:47	_log	2020/11/27 13:42:43,0471 | CdmCorpusDefinition | Unable to resolve the reference 'is.constrained' to a known object | /cdm-schema.microsoft.com/logical/core/applicationCommon/Contact/hasAttributes/attributesAddedAtThisScope/members/externalUserIdentifier/appliedTraits/is.constrained/(ref)
> ...
> 2020-11-27 16:43:43,312	ERROR	logger.py:47	_log	2020/11/27 13:43:43,3123 | CdmCorpusDefinition | Unable to resolve the reference 'resolvedFrom/CdmEntity' to a known object | /Account/attributeContext/Account/attributesAddedAtThisScope/attributesAddedAtThisScope/address/customerAddressInline/customerAddressAll/Address/extends/CdmEntity/definition/resolvedFrom/CdmEntity/(ref)
> 2020-11-27 16:43:43,316	ERROR	logger.py:47	_log	2020/11/27 13:43:43,3163 | CdmCorpusDefinition | Unable to resolve the reference 'resolvedFrom/ownerIdAttribute' to a known object | /Account/attributeContext/Account/attributesAddedAtThisScope/attributesAddedAtThisScope/address/customerAddressInline/customerAddressAll/Address/attributesAddedAtThisScope/attributesAddedAtThisScope/ownerIdAttribute/definition/resolvedFrom/ownerIdAttribute/(ref)

Why do these errors occur and how to fix it?

**Comment by dingbx** [comment]
Hi jayrumi,

You can use CdmStandardAdapter to fetch data from https://cdm-schema.microsoft.com/. Are you trying to fetch an entity from the CDM Standard Schema Store, resolve it and save it locally?

**Comment by jayrumi** [comment]
hi @dingbx ,

Thank you for the answer.
>  Are you trying to fetch an entity from the CDM Standard Schema Store, resolve it and save it locally?

Exactly.

>  You can use CdmStandardAdapter to fetch data from https://cdm-schema.microsoft.com/

How can I do it? Could you provide code example?

**Comment by llawwaii** [comment]
hi @jayrumi,

The storage has CdmStandardAdapter mounted by default, see [here](https://github.com/microsoft/CDM/blob/8aa7226e5c58d1363ad105bbd8e308a195793c1b/objectModel/Python/cdm/storage/storage_manager.py#L40) .

So you can remove the remote adapter, and try this 

>     manifest_abstract.entities.append('Account', 'cdm:/core/applicationCommon/Account.cdm.json/Account')

**Comment by jayrumi** [comment]
hi @llawwaii,

Thanks, it works. But nevertheless why I got errors when I was using RemoteAdapter?

**Comment by mfriscia7** [comment]
Hi @jayrumi, the RemoteAdapter was designed for cases where there are partitions at remote locations, and not designed for general use of loading cdm schema files.

**Comment by RonnieLew2** [comment]
https://github.com/microsoft/CDM/blob/8aa7226e5c58d1363ad105bbd8e308a195793c1b/objectModel/Python/cdm/storage/storage_manager.py#L40

**Comment by RonnieLew2** [comment]
[TB_SubExport_RonaldLewis_2017-01-15 (1).zip](https://github.com/microsoft/CDM/files/5685763/TB_SubExport_RonaldLewis_2017-01-15.1.zip)
[TB_SubExport_RonaldLewis_2017-01-15.zip](https://github.com/microsoft/CDM/files/5685765/TB_SubExport_RonaldLewis_2017-01-15.zip)
