### ISSUE TITLE
Support unstructured data 

### ISSUE THREAD

**Issue by data-modeling** [microsoft/CDM#205]
Can you create a CDM using structured and unstructured data? Would it work as an integration layer and can push data back to the data source?

**Comment by dingbx** [comment]
Hi,

Sorry for the late response. Can you please clarify what do you want to create with the CDM SDK? Do you want to create your own CDM schema files? Or maybe you are trying to describe your data with existing CDM schema files? For the integration layer, currently the CDM SDK adapters only allows users to read and write CDM related files such as *.cdm.json.

**Comment by data-modeling** [comment]
Thanks for getting back to me. I am trying to create a data model that can work well with Power Bi where I can also create a star schema so that end users have the ability to easily develop reports and dashboards.

Thanks

**Comment by mfriscia7** [comment]
If you have unstructured data, then it does not have a predictable schema which makes it sound like CDM would not be helpful for this case. You should be able to load data to PowerBI from a data source without using CDM. Maybe we need more clarification on why you think leveraging CDM would be helpful for your use case?

**Comment by data-modeling** [comment]
Thank you! Would it be possible to schedule a call to discuss my use case so we can determine whether CSM would work for my specific case?
Thanks,
Saber

**Comment by olegovanesyan** [comment]
Hi there,
CDM is not a generic data modeling language or data management runtime that can create data storage artifacts and/or be the layer to move data around. CDM describes data in Microsoft first party apps/solutions in a standard, well documented way. From what I can read in this thread, it is about general data modeling and subsequent reporting with Power BI using some heterogenous data. I suggest you check out resources available from Power BI e.g. https://www.youtube.com/watch?v=NLbW9Yft-5M that address data modeling with Power BI. 
Thanks for reaching out!

**Comment by Venkata1920** [comment]
Closing out since there has been no response.
