### ISSUE TITLE
[question] Are there methods to automate the creation of CDM-compliant entities in MySQL?

### ISSUE THREAD

**Issue by Steve-Carlin** [microsoft/CDM#209]
I'm a beginner learning to do db dev for an app idea and want to use CDM entities with MySQL Community on local PC.  Also have Visual Studio Community and Python installed.  Is there some way to take what's in the Entity Definition in the entity vizualizer and convert it to SQL Script so I don't have to manually recreate the tables/entities?  I tried copying the contents into this [ json to sql converter](https://www.convertjson.com/json-to-sql.htm) but didn't get any useful results.  Thanks for any help you can offer.

**Comment by mfriscia7** [comment]
Hi @Steve-Carlin, we do not currently have an easy way to do this natively. I do not know about MySQL but I know MSSQL has the ability to parse json, but it is not simple to do. I'm not sure if there is an easy way to do this.

**Comment by miroslavplese** [comment]
You can also study the [CDM to TSQL DDL conversion utility](https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/tree/master/Analytics/CDMUtilSolution) some folks built. It may give you useful pointers. Just keep in mind that this is not officially endorsed by Common Data Model team.

**Comment by Steve-Carlin** [comment]
Thank you kindly for taking the time to read, investigate and respond to my post.  It is greatly appreciated.
Godspeed.

**Comment by Steve-Carlin** [comment]
Thank you kindly for taking the time to investigate and answer.
Have a good week.
Godspeed
