### ISSUE TITLE
No partition "name" when saving in model.json

### ISSUE THREAD

**Issue by angandin** [microsoft/CDM#219]
When you save a CDM manifest in model format, partitions are correctly evaluated but the "name" attribute defined as required by the model specification is missing (https://docs.microsoft.com/en-us/common-data-model/model-json#partitions).
When you try to load the model.json by Power BI Data Flow, you receive an error

**Comment by surenderpawar** [comment]
Can you provide , sample code and power bi error snapshot please ?

**Comment by surenderpawar** [comment]
can you share the model.json as well ?

**Comment by angandin** [comment]
Hello,

attached you can find the model created automatically (model_before.json) **not readable** by Power BI Data Flow, and the one updated manually adding _"name":"pX"_ as partition name, **readable** by Power BI Data Flow

[model_before.json.txt](https://github.com/microsoft/CDM/files/5924098/model_before.json.txt)
[model_manualupdated.json.txt](https://github.com/microsoft/CDM/files/5924099/model_manualupdated.json.txt)

**Comment by mfriscia7** [comment]
Hello,

We have created a task for this issue and we will look into this very soon.

**Comment by surenderpawar** [comment]
Thanks for sharing . We will be fixing this future release. I will update here once done.

**Comment by llawwaii** [comment]
Hi,

We have fixed this issue in the latest release.
