### ISSUE TITLE
Python setup requires old version of regex that is missing wheels

### ISSUE THREAD

**Issue by amueller** [microsoft/CDM#221]
Hey!
Current installation instructions don't work on WSL (or I assume on linux or OS X) because they require gcc to be installed, as there are no binary wheels for regex for those platforms in the version that is required:
https://pypi.org/project/regex/2019.08.19/#files

The easiest solution would probably to bump the regex requirement to a more recent version, the current release has all the necessary wheels:
https://pypi.org/project/regex/#files

(my obvious work around was installing gcc)

**Comment by Venkata1920** [comment]
Hi @amueller, thanks for sharing the issue! We will file a task to update the regex soon. I'll respond on this thread once it's updated and published.

**Comment by victor-gutemberg** [comment]
Hello @amueller,

just wanted to let you know that the bug was fixed on our last release version 1.1.1.

closing this bug for now :)

**Comment by amueller** [comment]
Thank you!
