### ISSUE TITLE
Python tests not passing on fresh install on WSL

### ISSUE THREAD

**Issue by amueller** [microsoft/CDM#222]
Hey. I'm getting some errors, I think it might be an issue around paths.
The log is long so I attached it here, together with the conda list of all installed packages.
[conda_list.txt](https://github.com/microsoft/CDM/files/6013618/conda_list.txt)
[log.txt](https://github.com/microsoft/CDM/files/6013620/log.txt)

**Comment by Venkata1920** [comment]
Hi @amueller, could you provide a bit more context on the error? Is this happening completely within the WSL session? Or, is it happening when using VSCode with extensions pointing to the WSL session? Also, could you quickly verify that the pathname casing matches all the way through to the file(s)?

**Comment by amueller** [comment]
Yes, just WSL, no VSCode involved to keep it easy.

Which pathnames are you referring to? I didn't change anything, just running the tests.

**Comment by Venkata1920** [comment]
The path I was referring to was for the files in the log. Thanks for the quick response! We have identified the issue now as folder casing within the tests themselves and have a task now to fix the same. I'll update this thread once the issue is fixed and an update has been published.

**Comment by amueller** [comment]
Great, thank you!

**Comment by Venkata1920** [comment]
The folder casing has changed and the tests mostly pass now. We have one more change to go which will come along with the next SDK release (end of the month). Please raise the issue again if you see failures next month.
