### ISSUE TITLE
can't import python module as module name is not a valid python identifier

### ISSUE THREAD

**Issue by amueller** [microsoft/CDM#223]
After running a ``pip install``, I don't see how to import the module, as the name is defined as ``commondatamodel-objectmodel``, which is not a valid Python identifier (because of the dash). Is that on purpose? Given that the folder name is ``cdm``, having the name be ``cdm`` might be good?

cdm is taken on pypi but maybe we can ask them to free the name as it seems stalled?
https://pypi.org/project/cdm/

**Comment by absognety** [comment]
you can import using ` from cdm import objectmodel` it is similar to installing `scikit-learn` and importing `linear_model` using `from sklearn import linear_model`

**Comment by amueller** [comment]
huh, you're right, I must have messed something up. Clearly I misremembered how we did that in sklearn.
