### ISSUE TITLE
Event CDM - Venue to Building Relationship

### ISSUE THREAD

**Issue by priyankanadathur** [microsoft/CDM#224]
I looked at the documentation and it says that the Venue to Building is 1 to M (see link below) but the underlying database is not set up as such. The relationship is set up as M to 1 and cannot be modified/deleted either.

Is this a bug or am I missing anything here?

[](https://docs.microsoft.com/en-us/common-data-model/schema/core/applicationcommon/foundationcommon/crmcommon/solutions/marketing/eventmanagement/venue)

**The Venue describes the location at which all event sessions and activities take place. A single event venue can be comprised of zero or more buildings, each of which can have zero or more rooms where sessions take place.**

**Comment by Venkata1920** [comment]
hi @priyankanadathur, there's no link provided in your issue but I presume it is [this](https://docs.microsoft.com/en-us/common-data-model/schema/core/applicationcommon/foundationcommon/crmcommon/solutions/marketing/eventmanagement/venue). Anyways, could you elaborate on what you mean by underlying database? CDM, by itself, does not provide / support a physical storage.

**Comment by priyankanadathur** [comment]
Thanks @Venkata1920  - that is the link I wanted to reference. I am accessing the Event related tables via Power Apps - see screenshot below.

The out of the box relationship between Venue to Building is set up as M to 1 and I don't have an option to update or delete it.

**Comment by priyankanadathur** [comment]
Thanks @Venkata1920  - that is exactly the link I was looking to reference. 

I am accessing the Event related tables via Power Apps - see screenshot [here ](https://prnt.sc/1062vm5).

I highlighted the relationship in Yellow - the out of the box relationship between Venue to Building is set up as M to 1 and I don't have an option to update or delete it.

**Comment by Venkata1920** [comment]
Hi @priyankanadathur, thanks for response! This seems to be an issue with the way the Venue entity has been described in CDM. I'd think that the issue belongs with the solution owners. Still, I'll get back on the thread once I have more information on the next steps.

**Comment by priyankanadathur** [comment]
@Venkata1920 do you have any updates on this issue? We are in the early stage of product development and if this is truly an issue with no fix in sight we want to explore alternatives. Appreciate the help!

**Comment by Venkata1920** [comment]
Hi @priyankanadathur, sorry for the delayed response! We are engaging with the solution owners to get a fix for this issue but there's no clear timeline currently for when it will get done.  I can update the thread once we know of a timeline but it may be a while before we get to it.
