### ISSUE TITLE
CDM to Entity Framework

### ISSUE THREAD

**Issue by kdubious** [microsoft/CDM#229]
Is there an active project or automated way to create SQL Tables / Entity Framework Classes based on the models in the CDM?

**Comment by mfriscia7** [comment]
Hi @kdubious, unfortunately we currently do not have an automated way to do this.

**Comment by mfriscia7** [comment]
You could try checking this solution, though it was not built or officially endorsed by the CDM team: [CDM to TSQL DDL conversion utility](https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/tree/master/Analytics/CDMUtilSolution)
