### ISSUE TITLE
PowerApps support for manifest CDM (.manifest.cdm.json)?

### ISSUE THREAD

**Issue by subashsivaji** [microsoft/CDM#232]
When will the PowerApps and its Export to Data Lake feature support the latest Common Data Model format, the manifest (*.manifest.cdm.json)? Any ETA?

Currently it only supports model.json - however other Azure and Power BI services have evolved to use manifest model.

**Comment by sama-zaki** [comment]
The manifest feature for Export to Data Lake is currently being deployed and you should be able to access a preview within the next few weeks.

**Comment by subashsivaji** [comment]
@sama-zaki Its been 2 months since your update, any news about this? I don't see any announcement or documentation around this feature. If its already available please let us know how to enable manifest (*.manifest.cdm.json) for Azure Synapse Link for Dataverse (formerly known as Export to data lake). Thank you.

**Comment by sama-zaki** [comment]
Hi @subashsivaji, we have had some unexpected delays with this feature. We are working hard to make this available to our customers as soon as possible.
