### ISSUE TITLE
incompatible with Python 3.7 (Hard Pins causing compatibility issues)

### ISSUE THREAD

**Issue by dciborow** [microsoft/CDM#237]
A number of hard pins in this project have made it so we are unable to install along side things like Ray. I see dependabot running for Java.
Can this also be used to managed the python depedancies?

**Comment by dciborow** [comment]
#195

**Comment by llawwaii** [comment]
@dciborow Thanks for your suggestion. The latest version 1.2.1 is out now. This issue should be fixed.

**Comment by dciborow** [comment]
@llawwaii ,

We have a new issue. "lazy-object-proxy==1.3.1" is blocking python >=3.7. 

The dep is restricted to Python <=3.6.

**Comment by dciborow** [comment]
#239

**Comment by dciborow** [comment]
#240

**Comment by dciborow** [comment]
@llawwaii , can we confirm if this continuing issue can be fixed in the next release?

**Comment by dingbx** [comment]
hello, it will be a part of the next release.

**Comment by dingbx** [comment]
Closing this issue since the new release is available in this repo.
