### ISSUE TITLE
Need examples in c# for adding is.constrainedList traits

### ISSUE THREAD

**Issue by Akkilz** [microsoft/CDM#241]
I am trying to add constrainedToList, through sdk able to set true but need guidlines to add for the specific entity / attribute. 
I gone through doc's, its says via constantEntity ref to attribute can be achieved but need complete example.

https://docs.microsoft.com/en-us/common-data-model/sdk/logical-definitions

ConstantEntity - An association between an entity schema and a constant array of data values that exist only within the metadata documents. Used to represent tables of values.

![constant-entity-object](https://user-images.githubusercontent.com/11460269/119241565-ef30f500-bb46-11eb-9bbc-4c7f7c853095.png)

I tried to add appliedTraits in abstract site.cdm.json, in the entity visualizer it was showing properly 
![image](https://user-images.githubusercontent.com/11460269/119242863-070d7680-bb51-11eb-8d8b-9cbe5a5ffdaf.png)

when i resolve its not showing the resolved site.cdm.json, not sure what i am missing.
Plz find site.zip it has abstract & resolved version of site entity.

[site.zip](https://github.com/microsoft/CDM/files/6527284/site.zip)

**Comment by Akkilz** [comment]
After checking the scema doc's I was able to add in logical entity attribute & not sure this way is right & I need sample in c# for adding this.

![image](https://user-images.githubusercontent.com/11460269/119357996-af2d5780-bc97-11eb-8704-71714f182577.png)

`{
          "name": "Type",
          "dataType": {
            "dataTypeReference": "listLookup",
            "appliedTraits": [
              {
                "traitReference": "does.haveDefault",
                "arguments": [
                  {
                    "entityReference": {
                      "explanation": "The constantValues below correspond to the attributes of the 'listLookupValues' entityShape which are: {languageTag, displayText, attributeValue, displayOrder}",
                      "entityShape": "listLookupValues",
                      "constantValues": [
                        [
                          "en",
                          "Education",
                          "Education",
                          "0"
                        ],
                        [
                          "en",
                          "Health Care",
                          "Health Care",
                          "1"
                        ]
                        
                      ]
                    }
                  }
                ]
              }
            ]
          },
          "description": "Type of site",
          "maximumLength": 75,
          "valueConstrainedToList": true

        }`

![image](https://user-images.githubusercontent.com/11460269/119358319-0501ff80-bc98-11eb-963a-a061ed98f59e.png)

**Comment by llawwaii** [comment]
Hi @Akkilz,
We actually have a [sample](https://github.com/microsoft/CDM/blob/276a8b28de0fb68400e03edb608e5c77211b675e/samples/6-create-net-new-entities/code-cs/create-net-new-entities/Program.cs#L205) to show how to add a trait reference to `means.relationship.verbPhrase` which is similar to `is.constrainedList`, please check the both traits' definitions below:

 ```json
{
    "traitName": "is.constrainedList",
    "extendsTrait": "is",
    "explanation": "the values of an attribute are taken from or looked up from a fixed list of possibilities",
    "hasParameters": [
      {
        "name": "defaultList",
        "dataType": {
          "dataTypeReference": "entity",
          "appliedTraits": [
            {
              "traitReference": "means.entityName.specific",
              "arguments": [
                "listLookupValues"
              ]
            }
          ]
        }
      }
    ],
    "associatedProperties": [
      "valueConstrainedToList"
    ]
 },
 {
    "traitName": "means.relationship.verbPhrase",
    "extendsTrait": "means.relationship",
    "explanation": "The Verb Phrase used to model the relationship between the FROM entity and the TO entity.",
    "hasParameters": [
      {
        "name": "verbPhrase",         
        "explanation": "the localized Verb Phrase",
        "dataType": {
          "dataTypeReference": "entity",
          "appliedTraits": [
            {
              "traitReference": "means.entityName.specific",
              "arguments": [
                "localizedTable"
              ]
            }
          ]
        }
      }
    ]
  }
```  
  
The following code is copied from the [sample 6-create-net-new-entities](https://github.com/microsoft/CDM/blob/276a8b28de0fb68400e03edb608e5c77211b675e/samples/6-create-net-new-entities/code-cs/create-net-new-entities/Program.cs#L205)

```c#

// The purpose "meaningOfRelationshipVerbPhrases" is from /samples/example-public-standards/foundations.cdm.json
// With the use of this purpose, two additional traits ("means.relationship.verbPhrase" and "means.relationship.inverseVerbPhrase") will be added by default
// as they are attached to the purpose definition.
CdmPurposeReference purposeRef = cdmCorpus.MakeRef<CdmPurposeReference>(CdmObjectType.PurposeRef, "meaningOfRelationshipVerbPhrases", false);

// You can add your own argument to the additional traits 
// The trait "means.relationship.verbPhrase" is also from /samples/example-public-standards/foundations.cdm.json
// This trait states that the data type it requires is an entity "localizedTable", which allow you to define phrases in different languages
CdmTraitReference forwardPurposeTraitReference = cdmCorpus.MakeObject<CdmTraitReference>(CdmObjectType.TraitRef, "means.relationship.verbPhrase", false);

List<List<string>> forwardDescriptions = new List<List<string>> { 
    new List<string>() { "en", $"{customMessage} - Forwards" }, 
    new List<string>() { "cn", "正向" } 
};

var forwardConstEntDef = cdmCorpus.MakeObject<CdmConstantEntityDefinition>(CdmObjectType.ConstantEntityDef, null, false);
forwardConstEntDef.ConstantValues = forwardDescriptions;

// The entity "localizedTable" is from /samples/example-public-standards/foundations.cdm.json
forwardConstEntDef.EntityShape = cdmCorpus.MakeRef<CdmEntityReference>(CdmObjectType.EntityRef, "localizedTable", true);
forwardPurposeTraitReference.Arguments.Add(null, cdmCorpus.MakeRef<CdmEntityReference>(CdmObjectType.EntityRef, forwardConstEntDef, true));

purposeRef.AppliedTraits.Add(forwardPurposeTraitReference);
  ```
  
 After running the sample, you would get the following in the `CustomAccount.cdm.json`:

```json
"purpose": {
  "purposeReference": "meaningOfRelationshipVerbPhrases",
  "appliedTraits": [
    {
      "traitReference": "means.relationship.verbPhrase",
      "arguments": [
        {
          "entityReference": {
            "entityShape": "localizedTable",
            "constantValues": [
              [
                "en",
                "Non-simple resolution guidance sample - Forwards"
              ],
              [
                "cn",
                "正向"
              ]
            ]
          }
        }
      ]
    }
  ]
}
```

**Comment by Akkilz** [comment]
```
entityAttribute.ValueConstrainedToList = true;

                CdmDataTypeReference dataTypeRef = cdmCorpus.MakeRef<CdmDataTypeReference>(CdmObjectType.DataTypeRef, "listLookup", true);
                CdmTraitReference forwardDataTypeTraitReference = cdmCorpus.MakeObject<CdmTraitReference>(CdmObjectType.TraitRef, "does.haveDefault", false);
                List<List<string>> forwardDescriptions = new List<List<string>>();
                var index = 0;
                property.Enum.ForEach(item =>
                {
                    forwardDescriptions.Add(new List<string>()
                    {
                        "en", item, item, index.ToString()
                    });

                    index++;
                });

                var forwardConstEntDef = cdmCorpus.MakeObject<CdmConstantEntityDefinition>(CdmObjectType.ConstantEntityDef, null, false);
                forwardConstEntDef.Explanation = "The constantValues below correspond to the attributes of the 'listLookupValues' entityShape which are: {languageTag, displayText, attributeValue, displayOrder}";
                forwardConstEntDef.ConstantValues = forwardDescriptions;
                forwardConstEntDef.EntityShape = cdmCorpus.MakeRef<CdmEntityReference>(CdmObjectType.EntityRef, "listLookupValues", true);
                forwardDataTypeTraitReference.Arguments.Add(null, cdmCorpus.MakeRef<CdmEntityReference>(CdmObjectType.EntityRef, forwardConstEntDef, true));
                dataTypeRef.AppliedTraits.Add(forwardDataTypeTraitReference);

                entityAttribute.DataType = dataTypeRef;
```

I am trying to achieve this,
![image](https://user-images.githubusercontent.com/11460269/119415826-ed4f6900-bce1-11eb-9b99-ab9b8f222740.png)

Instead i got 
![image](https://user-images.githubusercontent.com/11460269/119415888-0526ed00-bce2-11eb-924c-ebe4efa50c2d.png)

I am not sure what i am missing & purpose is working fine, as per cdm doc's i needed listLookup default values.
Is there any guidelines is available ?

**Comment by Akkilz** [comment]
my bad its working, 
CdmDataTypeReference dataTypeRef = cdmCorpus.MakeRef<CdmDataTypeReference>(CdmObjectType.DataTypeRef, "listLookup", false);

**Comment by Akkilz** [comment]
i am able to do dataType field list lookup in c#
