### ISSUE TITLE
Global pattern & regular expression, which one to use ?

### ISSUE THREAD

**Issue by Akkilz** [microsoft/CDM#243]
Which one to use global pattern or regular expression for data partition pattern. I see an example for regular expression, is there any example avaiable for glabal pattern (c#) & use cases ?

```
{
          "name" : "NewPartitionPattern",
          "rootLocation" : "dataFiles/financials/costTransaction/2021/May/",
          "globPattern" : "CostTransaction-66d13d72db4149a69adbaf095c187f3f*.csv",
          "exhibitsTraits" : [
            {
              "traitReference" : "is.partition.format.CSV",
              "arguments" : [
                {
                  "name" : "columnHeaders",
                  "value" : "true"
                },
                {
                  "name" : "delimiter",
                  "value" : ","
                },
                {
                  "name" : "escape",
                  "value" : "\\"
                },
                {
                  "name" : "encoding",
                  "value" : "utf-8"
                },
                {
                  "name" : "quote",
                  "value" : "\""
                }
              ]
            }
          ]
        }
```

**Comment by dingbx** [comment]
You can use either globpattern or regular expression based on your habit.
Definition of data partition pattern can be found [here](https://docs.microsoft.com/en-us/common-data-model/1.0om/api-reference/cdm/datapartitionpattern).
And the usage of glob pattern and regular expression is in [sample 7-search-partition-pattern](https://github.com/microsoft/CDM/blob/master/samples/7-search-partition-pattern/code-cs/search-partition-pattern/Program.cs) line 71 - 73.

Is your dataPartitionPattern above not working?
