### ISSUE TITLE
CDM Editor

### ISSUE THREAD

**Issue by samirelouasbi** [microsoft/CDM#244]
Hi,
There are any editor that permit to edit and modify json files in CDM. The goal is to create my custom CDM using the existing files in CDM Folder.
I want to create a folder like Healtcare.
Thank you for your answer and any suggestions are very welcome.

**Comment by dingbx** [comment]
Hello,

These schemas are autogenerated using internal microsoft tooling from dataverse (dynamics) solutions. Currently there is not an editor specifically for CDM files. You can still use VSCode as a tool to create your own manifests and entities from the existing schema documents.

Please check healthcare [schema](https://github.com/microsoft/CDM/tree/master/schemaDocuments/Healthcare) and [documentation](https://docs.microsoft.com/en-us/common-data-model/schema/core/industrycommon/healthcare/healthcare-overview).

**Comment by samirelouasbi** [comment]
thank you so much :)
