### ISSUE TITLE
Python Dependency blocks latest azure-keyvault

### ISSUE THREAD

**Issue by dciborow** [microsoft/CDM#250]
The latest release of Azure Key Vault requires msal>1.12.0.

**Comment by Venkata1920** [comment]
Hi @dciborow, thanks for bringing this up. The requirement does seem valid and change is simple too. But, there are other dependencies that need to be evaluated. I will look into this and get back on this thread by tomorrow.

**Comment by Venkata1920** [comment]
Hi @dciborow, there doesn't seem to be any broken dependencies even after loosening the version. So, we will take this change up in our upcoming release. Thanks for the feedback! I'll close this out once the new release is published to GitHub.

**Comment by Venkata1920** [comment]
Hi @dciborow, the latest version of the CDM SDK contains this change now.
