### ISSUE TITLE
CdmEntityDefinition.getPrimaryKey() ClassCast Exception

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#257]
Hello again, came across this exception:

TraitToPropertyMap.class, line 165
  case PRIMARY_KEY:
        final CdmTypeAttributeDefinition attRef = (CdmTypeAttributeDefinition)
            fetchTraitReferenceArgumentValue(
                this.fetchTraitReference(CdmTraitName.IS_IDENTIFIED_BY.toString(), onlyFromProperty),
                "attribute"); // TODO-BQ: This may break since unchecked casting
        if (attRef != null) {
          return attRef.fetchObjectDefinitionName();
        }
        break;
Trace:

Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class com.microsoft.commondatamodel.objectmodel.cdm.CdmTypeAttributeDefinition (java.lang.String is in module java.base of loader 'bootstrap'; com.microsoft.commondatamodel.objectmodel.cdm.CdmTypeAttributeDefinition is in unnamed module of loader 'app')
	at com.microsoft.commondatamodel.objectmodel.utilities.TraitToPropertyMap.fetchPropertyValue(TraitToPropertyMap.java:167)
	at com.microsoft.commondatamodel.objectmodel.utilities.TraitToPropertyMap.fetchPropertyValue(TraitToPropertyMap.java:100)
	at com.microsoft.commondatamodel.objectmodel.cdm.CdmEntityDefinition.getPrimaryKey(CdmEntityDefinition.java:949)

**Comment by dingbx** [comment]
Thanks for posting your problem here and sorry for the late response. Can you please also provide what the API you called to trigger this exception?

**Comment by cashel1** [comment]
Hello dingbx,

After generating the corpus instance (per the read manifest example), the code triggering the exception  is as follows:

CdmManifestDefinition manifest = cdmCorpus.<CdmManifestDefinition>fetchObjectAsync(manifestPath).join();

	for (final CdmEntityDeclarationDefinition entityDeclaration : manifest.getEntities()) {
		System.out.println("Reading the entity schema for " + entityDeclaration.getEntityName() + " located at " + entityDeclaration.getEntityPath());

		CdmEntityDefinition entSelected = cdmCorpus.<CdmEntityDefinition>fetchObjectAsync(entityDeclaration.getEntityPath(),manifest).join(); // Gets the entity object from the doc.

		writeEntityProperties(entWriter, vals, cdmCorpus, entSelected, entityDeclaration, module, targetDir);

	}
	
	static void writeEntityProperties(CsvWriter entWriter, ArrayList<String>vals, CdmCorpusDefinition cdmCorpus, final CdmEntityDefinition entity, 
			final CdmEntityDeclarationDefinition entityDec, String module, String targetDir) {

		CdmEntityReference entityRef = entity.getExtendsEntity();
		vals.add(entity.getDisplayName());			// commonClassName
		vals.add(entity.getPrimaryKey());			// BREAKS, REPORT
	}

Also, when accessing the attributes I am able to get the primary key via:
vals.add(getStringVal(typeAttributeDefinition.fetchIsPrimaryKey()));		// primaryKey

Thanks
