### ISSUE TITLE
No explanation on how to use Visual Entity Navigator, can't see relationships

### ISSUE THREAD

**Issue by simes1** [Microsoft/CDM#26]
So the Visual Entity Navigator here https://microsoft.github.io/CDM/ seems a potentially useful tool to understand which bits of an entity come from which bits of Dynamics 365 and Microsoft's various add-ins and add-ons for it..  (Something that has become increasingly hard to understand and keep up with recently).  But without some more information I'm really not sure how to use it effectively.

For example at the moment I don't seem to be able to see relationships properly.  I can see them to some limited extent in terms of lookup fields and the "Used by Selected" and "Uses the Selected" colours when I click on an entity and a list of related entities if I double-click on an entity.

But that's it - nothing about relationship cardinality, cascade rules, naming etc. etc.  Am I missing something?

Regards

--
Simon

**Comment by JeffBern** [comment]
Simon, you are not missing anything. The depth of information you are looking for about Dynamics relationships is not available currently in the CDM documents. This is good feedback regarding cardinality, enforcement, etc. I will make them feature requests. To explain the gap: the CDM documents aim to be somewhat storage or source platform agnostic. As such, the ones derived from Dynamics entities are missing some of the details that would make them full fidelity from the source system. If there are other properties that are not about Dynamics only but rather are about helping to understand the entities and how they are related and what they mean semantically, then we will add them.
