### ISSUE TITLE
CodeList Labels and Values

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#260]
I do not understand the implementation of certain default value CodeLists that have 5 values versus the more typical 4 value lists.

Per the followings trait, this list has 5 values, due to what appears to be an additional comma separator that I'm assuming is to show the user the numeric value associated with the code.  
If this is the case, the label 'Open, 1' is not aligned with the actual numeric value of 0.

Service Module, CaseResolution
path=CaseResolution/hasAttributes/statusCode
trait=does.haveDefault=Constant:[[en, Open, 1, 0, 0][en, Closed, 2, 1, 1][en, Canceled, 3, 2, 2]]

This is another example where the label/sequence and value appear to be more random.			

Service Module, Service
path=Service/hasAttributes/initialStatusCode
trait=does.haveDefault=Constant:[[en, Requested, 1, 0, 0][en, Tentative, 2, 1, 0][en, Pending, 3, 2, 0][en, Reserved, 4, 3, 0][en, In Progress, 6, 4, 0][en, Arrived, 7, 5, 0][en, Completed, 8, 6, 1][en, Canceled, 9, 7, 2][en, No Show, 10, 8, 2]]
			
Please advise if I'm misunderstanding the use of the '5 value' codeList.

Thanks

**Comment by duncandavenport** [comment]
Good Morning, Cashel! 
The constant-values lists that are associated with Traits actually come in a number of different shapes. In each case, the list of "columns" has specific meanings. These can be found in the underlying CDM json files in the "explanation" of the constant-values set.
In this case, both of these represent the "listLookupCorrelatedValues" shape. 
_"The constantValues below correspond to the attributes of the 'listLookupCorrelatedValues' entityShape which are: {languageTag, displayText, attributeValue, displayOrder, correlatedValue}"_
In general, the correlated value value is used to represent a status - a sub-state, so to speak.

Let us know if you have further questions concerning the definition of these constant value definitions.
Thanks, Cashel!

**Comment by duncandavenport** [comment]
As an additional note, here are the attributes of the five most common internal shapes used to describe constant value sets. The indentation represent extension: everything derives from localizedTable
![image](https://user-images.githubusercontent.com/73262618/134551909-e694306b-6579-4a9d-a77f-9df88b701777.png)

**Comment by cashel1** [comment]
OK, thanks Duncan
