### ISSUE TITLE
Incomplete C# Documentation

### ISSUE THREAD

**Issue by Grauenwolf** [microsoft/CDM#267]
The readme file says,

> The Common Data Model library uses assembly lookup to discover and register additional formats. Absense of these assemblies will raise System.IO.FileNotFoundException which will be captured by the Common Data Model library to allow the normal operation to continue.

But nowhere does it say what these additional assemblies are or where to get them.

**Comment by Grauenwolf** [comment]
A couple things. 

First, telling me only tells me. The appropriate readme files need to be updated.

Secondly, that list doesn't really help. The readme file should explain what those libraries are and why one would want to use them. As an ignorant developer, it just makes me ask more questions such as.

1. Why are they assemblies at all? If they are just "formats", shouldn't they just be additional cdm.json files?
2. If they really should be assemblies, why aren't they listed as normal dependencies? Is there a reason why I wouldn't want to use them?
3. Why would they throw an FileNotFound exception instead of checking to see if the file exists first?

**Comment by mfriscia7** [comment]
We have updated these docs in our latest release.
