### ISSUE TITLE
Readme file needs to better explain why this project exists

### ISSUE THREAD

**Issue by Grauenwolf** [microsoft/CDM#269]
I've looked through all of the code and I don't see a single C# entity anywhere. I was expecting to be able to grab a library with all of the CMD entities defined as classes so I could use them in my application. But there's just that weird explorer thing that presents the entity defintion is a... well to be honest.., confusing and ultimately useless format.

Could we get a link in the main readme to the actual CDM project with actual C# entites for us to use?

**Comment by olegovanesyan** [comment]
Hi Grauenwolf,
The purpose and value of the this SDK is to provide consistent way to read, edit and create cdm documents. It does not have a goal of creating C# classes with operational API to manage the data that entities describe. The SDK can be used as CDM reader/writer from solutions that take advantage of the metadata format. I think it is the question of the what outcome would you like to accomplish and is the SDK a specific tool for that.
