### ISSUE TITLE
C# CdmCorpusDefinition.SetEventCallback Should be an Event

### ISSUE THREAD

**Issue by Grauenwolf** [microsoft/CDM#271]
As per .NET conventions and the Framework Design Guidelines, `CdmCorpusDefinition.SetEventCallback` should be exposed as an event rather than a callback object. 

Any filtering on `CdmStatusLevel` can be done by the event handlers. (Plural because there may be multiple listeners to this event.)

**Comment by mfriscia7** [comment]
Hi @Grauenwolf,
SetEventCallback was created as a callback to be consistent with the other languages that the SDK is implemented in. This change would be a breaking change and is not something that we are planning on taking on.

**Comment by Grauenwolf** [comment]
Doing it the right way is not a breaking change. You can add a real event and leave the improperly designed `SetEventCallback` as a obsolete method.

Trying to be "consistent" across completely different platforms just leads to a poor developer experience on all of them. The SDK should be consistent with each language/platform's conventions and design patterns.

**Comment by Venkata1920** [comment]
Thanks for the feedback and suggestions, @Grauenwolf! But, there are specific requirements that we need to follow internally and hence will not be able to take this request into consideration.
