### ISSUE TITLE
C# XMl Docs Are Missing From Nuget Package

### ISSUE THREAD

**Issue by Grauenwolf** [microsoft/CDM#272]
The `Microsoft.CommonDataModel.ObjectModel.xml` file is not being generated. Which means anyone consuming the NuGet package won't get the XML Docs for the classes and members.

**Comment by mfriscia7** [comment]
Hi @Grauenwolf,
Thanks for the suggestion, I will create a task for this and we will try to get this fixed soon

**Comment by mfriscia7** [comment]
Hi @Grauenwolf,
We are open to accepting pull requests to the repo, especially for issues that are specific to a single language. Feel free to open a pull request if you would like.
