### ISSUE TITLE
C# CdmCorpusDefinition and StorageManager Should be IDisposable

### ISSUE THREAD

**Issue by Grauenwolf** [microsoft/CDM#273]
CdmCorpusDefinition should be marked as IDisposable and call `Dispose` on `StorageManager`.

StorageManager should be marked as IDisposable and call `Dispose` on any `StorageAdapter` that is itself `IDisposable`.

**Comment by mfriscia7** [comment]
Hi @Grauenwolf,
Thanks for the suggestion, this is something we will consider adding though it is not currently a high priority item for us.
