### ISSUE TITLE
Naming Convention for the Common Data Model (CDM)

### ISSUE THREAD

**Issue by berikorazov** [microsoft/CDM#280]
Is there Naming Convention for the Common Data Model (CDM)?
For example, how should to name a person according to CDM, John Smith or JOHN SMITH or else?

**Comment by duncandavenport** [comment]
When it comes to naming conventions for defining objects like entities and attributes, we try to adhere to camel-casing as a JSON standard. Anyplace that schema elements are defined, we expect camel-case. When making reference to CDM objects, you can expect camel-case to be used, remembering that JSON is case sensitive.
What you have shown with "John Smith" appears to be your _data_ value. What is managed by CDM is primarily _schema_, not data. The only place data definitions tend to appear is in Constant entities:  representations of known enumerations (what Dataverse calls "choices" and used to call "option sets"). In these cases the values in the Constant entity can be in whatever format makes sense for the context - they generally map to sets of values already defined by the application.

FWIW, CDM is not designed to be a place to keep the data, but as a way to represent the schema that keeps the data.

**Comment by berikorazov** [comment]
Many thanks for your quick and clear answer!

**Comment by duncandavenport** [comment]
Hello berikorazov. We note that you re-opened this issue immediately upon closing it. Was that intentional? If you have any further questions, please let us know. Otherwise, would you consider this issue closed?
