### ISSUE TITLE
Convert CdmEntityDeclarationDefinition to CdmEntityDefinition

### ISSUE THREAD

**Issue by iliriani** [microsoft/CDM#288]
Hello, I am trying to read all the entities from the CDM and transform them into another format (in java code). The issue is that when I read all entities from a given manifest (manifest.getEntities()) I get only a collection of CdmEntityDeclarationDefinition entities and I need to have them as CdmEntityDefinition so I can get all the related data for any entity.

**Comment by victor-gutemberg** [comment]
Hello @iliriani,

a manifest contains CdmEntityDeclarationDefinition, which is just a pointer to the actual entity definition. To retrieve the CdmEntityDefinition you need to call FetchObjectAsync.

Please take a look at our [samples](https://github.com/microsoft/CDM/tree/master/samples) for examples of how to use the CDM SDK.

`
for(CdmEntityDeclarationDefinition entDeclaration : manifest.getEntities()) {
    CdmEntityDefinition entity = corpus.<CdmEntityDefinition>fetchObjectAsync(entDeclaration.getEntityPath(), manifest).join();
}
`
