### ISSUE TITLE
CDM Public sector

### ISSUE THREAD

**Issue by popujol** [microsoft/CDM#290]
Hello
Is there a CDM for public sector (citizen would be the contacts for instance)
Thank you

PO

**Comment by olegovanesyan** [comment]
Hello and thank you for reaching out. Dynamics family of products has various public sector functionality. We’ve published the F&O schema to the CDM GitHub. There no “CDM for public sector” container for entities. Instead, it’s public sector functionality spread throughout the rest of the relevant schema. For reference - https://docs.microsoft.com/en-us/common-data-model/schema/core/operationscommon/overview; GitHub location of schema documents - https://github.com/microsoft/CDM/tree/master/schemaDocuments
Thank you
