### ISSUE TITLE
Please can Nationality be added to contact

### ISSUE THREAD

**Issue by skoya** [microsoft/CDM#291]
Please can the nationality of the contact record be added to the Marketing Contact record, ideally using ISO 3166?

[ISO  3116](https://www.iban.com/country-codes#:~:text=Country%20Codes%20Alpha-2%20%26%20Alpha-3%20%20%20,%20%20016%20%2079%20more%20rows%20)

OR is it better to create a marketing list that is country code specific so that contacts can be targetted?

**Comment by yukom-ms** [comment]
Hello skoya, would you please add your request to the [D365 Marketing Ideas site](https://experience.dynamics.com/ideas/categories/?forum=dfa5b83d-9e4c-e811-a956-000d3a1bef07&forumName=Dynamics%20365%20Marketing) so we can get the community to vote on this? 
Thank you!
