### ISSUE TITLE
Descriptions on Transportation Entities

### ISSUE THREAD

**Issue by kevine323** [microsoft/CDM#293]
There are no descriptions on any of the Transportation entities. We're very interested in the transportation specific CDM but without a description of the field, it's hard to understand if we're using it correctly.

**Comment by llawwaii** [comment]
Hi @kevine323, thanks for your recommendation. Can you check out the schema from [here](https://github.com/microsoft/CDM/tree/master/schemaDocuments/core/operationsCommon/Tables/SupplyChain/Transportation) directly to for now? Thanks!

**Comment by Miki456wang** [comment]
Hi @kevine323 , unfortunately, we don't have better documentation available now.  I would suggest you go through our support team, log a specific request like what information you are looking for, what entities you are interested in.  Our supporting team or PM should be able to provide you some level details for some request.
