### ISSUE TITLE
Samples do not compile

### ISSUE THREAD

**Issue by joern-schlingensiepen** [microsoft/CDM#307]
The project file
    objectModel\CSharp\Microsoft.CommonDataModel.ObjectModel\Microsoft.CommonDataModel.ObjectModel.csproj

does contain
`
 <ItemGroup>
    <Compile Include="..\StrongNameKey\AssemblyRef.cs" Link="AssemblyRef.cs" />
  </ItemGroup>
`
but this file is not shipped with the repo.

**Comment by llawwaii** [comment]
@joern-schlingensiepen Thanks for reporting it, this line should be removed in the .csproj file. We will remove it in the next release. The workaround for now is to remove it on your end locally, you should be able to compile it.

**Comment by mfriscia7** [comment]
@joern-schlingensiepen We have released a new version that fixed this issue so you do not need to manually remove this entry.
