### ISSUE TITLE
CDM Format and project information

### ISSUE THREAD

**Issue by jocooler** [microsoft/CDM#31]
This work looks really promising. We're also working on coming up with a standard set of entities to model work from a performance perspective. Are you working from a standard way of describing entities? Are the .cdm.json and .dplx based on a standard somewhere?

Is this project open source or seeking to become a community/shared standard?

**Comment by jugaadi** [comment]
Few questions: 
1. Is there any update on 1.0 release? 
2. What are the updates on Open Data Initiative?

PS: I would also like to point out a similar initiative [here](https://github.com/openintegrationhub/openintegrationhub).

**Comment by AKASouthways** [comment]
Dear Theresa,

I am currently working on my Master Thesis in which I am incorporating CDM as a point of interest. Is it possible to get your contact information so I can ask you some questions if necessary regarding CDM?

Kind regards, 

Mike

**Comment by stamsooo** [comment]
Mike,

Can you send me a copy of your Master Thesis as soon as it is finished?

Robert Stamsnijder
R.Stamsnijder@gmail.com
