### ISSUE TITLE
is.requiredAtLevel Trait Missing

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#312]
I'm am testing against a local copy of CDM 1.6, with the updated java maven pom.xml for the 1.6 version.
Review is limited to the applicationCommon->foundation->crmCommon->CustomerInsights->segment.cdm.json file.
For the segmentId field, the is.requiredAtLevel trait is not present.
The current CDM Entity Navigator on GitHub (shows as version 1.3 under Resolved tab) shows the segmentId field with the is.requiredAtLevel trait specified as systemrequired.
I checked the 1.3 and 1.3.1 schema files, and the trait was not specified there as well.
Is this trait inferred from the entity type or other CDM references?

Thanks

**Comment by victor-gutemberg** [comment]
Hello @cashel1, 

during resolution the CDM SDK converts the references and applies the traits that comes from them on the attribute. 
The `segmentId` attribute has a purpose `identifiedBy` from which the trait `is.requiredAtLevel` comes from. 

Marking an attribute as with purpose `identifiedBy` means that that attribute is a kind of primary key of an entity so it's value is always required.

**Comment by cashel1** [comment]
Need to double back here.  Forgot to update the client apis from elastic to open.
