### ISSUE TITLE
Missing Fields

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#313]
I'm am running against a local copy of CDM 1.6, with the updated maven pom.xml for the 1.6 version.
In this version, I'm seeing a new 'duplicate' message.  
This appears to identify classes that are extended in more dependent module, and otherwise 'not actionable'.
My working premise has always been that the latest/full schema definition is available in the associated xx.cdm.json file.
Are these two assumptions correct?

Did a quick audit against crmCommon->CustomerInsights->segment.cdm.json and the online CDM Entity Navigator, which shows as version 1.3.  
The CDM Navigator version lists the following fields (all near the bottom of the display) that are not in the segment.cdm.json file.
	activationStatus
	filterQuery
	memberIDs
	provisioningState
		
I checked the 1.3 and 1.3.1 schema files, and these fields were not specified there as well.	
	
Are these fields identified via some other reference mechanism?
	
Thanks

**Comment by victor-gutemberg** [comment]
hello @cashel1,

your assumption about the presence of a xx.cdm.json file along with the latest is correct. This is to ensure that systems that depend on a specific version of the schema are not broken when we release a new version.

About the extra attribute you're seeing, can you please double check that you're selecting crmCommon->CustomerInsights->segment.cdm.json and not crmCommon->marketing->segment.cdm.json.

I'm not able to see those extra attributes on the CustomerInsights solution, but they are present on the marketing solution.

**Comment by cashel1** [comment]
You are correct, these fields do appear under marketing.  

Thanks
