### ISSUE TITLE
interactions module errors

### ISSUE THREAD

**Issue by cashel1** [microsoft/CDM#314]
This follows on a closed issue, as it could not be replicated at the time.  One factor that occurred to me later was that the MS staff could
have been using a cloud based repository versus my use of a local copy of CDM.

I'm am running against a local copy of CDM 1.6, with the updated maven pom.xml for the 1.6 version and receiving the following
error messages for all the classes in the module. I have not experienced this issue with any other modules I've processed with
the java client.
				
I did see that the first schema listed below is version 0.9.2, so possibly its code updates related to later versions.
				
Reading entity schema ActivityContactDispatched located at ActivityContactDispatched.cdm.json/ActivityContactDispatched
ERROR: entity does not provide any schemas ActivityContactDispatched
Reading entity schema ActivityContactProcessingFailed located at ActivityContactProcessingFailed.cdm.json/ActivityContactProcessingFailed
ERROR: entity does not provide any schemas ActivityContactProcessingFailed
Reading entity schema ContactCheckedIntoEvent located at ContactCheckedIntoEvent.cdm.json/ContactCheckedIntoEvent
ERROR: entity does not provide any schemas ContactCheckedIntoEvent
Reading entity schema ContactRegisteredToEvent located at ContactRegisteredToEvent.cdm.json/ContactRegisteredToEvent		

Please re-review this issue to determine what could be throwing this error.

Thanks

**Comment by victor-gutemberg** [comment]
hello @cashel1,

For the schema files, we recommend only using the ones starting at 1.0 since this was when we made all the code and schema generally available.

As for the error messages, can you please provide more details about how you're seeing them?

**Comment by cashel1** [comment]
Hello Victor,
The activityContactDispatched.cdm.json file lists the following version info at the top of the file.  Reviewed several other files and they also show a document version < 1.0.  

The "documentVersion": "0.9.2",
  "jsonSchemaSemanticVersion": "1.0.0" 

The error messages I noted are the only items displayed, and they occur for each schema file.  I have not stepped thru the java code, but I'm guessing the 'entity does not provide any schemas' is referencing the document schema being less than 1.0 

Thanks

**Comment by mfriscia7** [comment]
Hi @cashel1,

These files should have been updated here as they have been internally. We will work on fixing this. In the meantime, you can remove the "documentVersion" line from the file and change the "is.CDM.entityVersion" trait to be "1.0" as well to fix it for you locally.

**Comment by mfriscia7** [comment]
The schemas have now been updated so I am closing this issue.
