### ISSUE TITLE
C# implementation?

### ISSUE THREAD

**Issue by MisinformedDNA** [Microsoft/CDM#33]
Is there a C# implementation of the spec? We are creating an ecommerce system and I think it would be helpful to build off of CDM. With PowerApps and Dynamics and other MS properties using or going to use CDM, I find it strange that I can't find an implementation of the schema. Are their plans to build one?

**Comment by theresapalmer** [comment]
Hi MisinformedDNA - the Common Data Service for Applications (that powers PowerApps and Dynamics) does implement CDM today through their solution/schema model, for example the healthcare schemas are included in the [Healthcare accelerator](https://appsource.microsoft.com/product/dynamics-365/msemr.healthcarecommondatamodel). 

We're working to improve the visibility and discoverability of theses additions within CDS, please add the suggestion to the PowerApps/CDS [ideas forum](https://powerusers.microsoft.com/t5/PowerApps-Ideas/idb-p/PowerAppsIdeas/label-name/common%20data%20service%20for%20apps)

In addition we're working on a C# set of libraries to read/write the schema files, similar to the typscript libraries in this repo. If you're interested in using CDM outside of CDS, in Azure Data Lake Gen2 for example, those might be interesting. Please read more in the [documentation](https://docs.microsoft.com/common-data-model/data-lake).

**Comment by JasonSowers** [comment]
@theresapalmer 

> In addition we're working on a C# set of libraries to read/write the schema files, similar to the typscript libraries in this repo. 

I'm curious if this was ever released?
