### ISSUE TITLE
TokenProviderAsync.GetTokenAsync should accept CancellationToken

### ISSUE THREAD

**Issue by tovyhnal** [microsoft/CDM#333]
When we are implemeting GetTokenAsync, our implementation requires CancellationToken, which we can not pass because GetTokenAsync does not accept that.

It is a good practice to accept CancellationToken for async calls.

This is how current implementation looks like:

```
        public async Task<string> GetTokenAsync()
        {
            var accessToken = await this.authenticator
                .GetAccessToken(
                    tenantId: this.tenantId,
                    resource: DataLakeResource,
                    CancellationToken.None); // Current version of TokenProviderAsync does not support accepting cancellation token

            return $"Bearer {accessToken}";
        }
```

**Comment by mfriscia7** [comment]
Hi @tovyhnal, thanks for bringing this to our attention. I have created a task for this issue, and we will provide updates as the changes are made.
