### ISSUE TITLE
Avoid setting JsonConvert.DefaultSettings

### ISSUE THREAD

**Issue by mgreen** [microsoft/CDM#334]
In PersistenceLayer.cs, the Newtonsoft JsonConvert default settings are overwritten. This is a global default that can break serialization for consumers who are also using JsonConvert and would likely not be expecting this behavior.

https://github.com/microsoft/CDM/blob/9de479beb4b0a223db08f9feff140498d598f333/objectModel/CSharp/Microsoft.CommonDataModel.ObjectModel/Persistence/PersistenceLayer.cs#L142-L147

Instead, one of the JsonConvert overloads accepting a settings object could be used.

**Comment by llawwaii** [comment]
Hi @mgreen, thanks for bringing this to our attention. I have created a task for this issue, and we will provide updates as the changes are made.
