### ISSUE TITLE
How to create relationships between entities

### ISSUE THREAD

**Issue by deepspraj** [microsoft/CDM#336]
I do have around 15 entities and want to create relationship between those.
I was able to create entity.cdm.json file using <a href="https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/data-sources/apache-spark-cdm-connector#explicit-write---using-an-entity-defined-in-the-cdm-github-1">MS Documentation</a> but <a href="https://github.com/microsoft/CDM/blob/master/objectModel/TestData/Cdm/Relationship/TestRelationshipToMultipleEntities/Input/A.cdm.json">entity.cdm.json</a> in cdm's github repository have "foreignKeyAttribute" clause.
Tried to figure exactly how this clause came but was unable to do. As there are few blogs and videos on internet regarding cdm and none talks about creating relationship for entities.
Can you please guide me on this ??

Thank You !!

**Comment by llawwaii** [comment]
Hi @deepspraj, please take a look at [this sample](https://github.com/microsoft/CDM/tree/master/samples/6-create-net-new-entities); however, please note [Attribute Resolution Guidance](https://learn.microsoft.com/en-us/common-data-model/1.0om/api-reference/cdm/attributeresolutionguidance) is being deprecated in favor of Projections, learn more [here](https://docs.microsoft.com/en-us/common-data-model/sdk/convert-logical-entities-resolved-entities#projection-overview).

more useful links:  https://learn.microsoft.com/en-us/common-data-model/sdk/projections/replaceasforeignkey
https://github.com/microsoft/CDM/tree/master/samples/8-logical-manipulation-using-projections

Hope this can help. Feel free to ask more questions.

**Comment by Venkata1920** [comment]
Closing this issue as there has been no update. Please re-activate if there are additional queries / issues with creating relationships

**Comment by deepspraj** [comment]
@llawwaii Thank you for guiding us.
As stated by you the sample no 6 is supported by C# and Java. Can you please show me the path where I can get to know how to generate relationships between entities using Python? 

When we create relationships in manifest file is it necessary to mention primary and foreign key attribute in entity.cdm.json file   ?
And when we try to generate relationship between entities using C# code in manifest file, this [code ](https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/data-sources/apache-spark-cdm-connector#explicit-write---using-an-entity-defined-in-the-cdm-github-1) doesn't create entity.cdm.json file respectively for entities but updates the manifest file with partition status of each entity.
