### ISSUE TITLE
Support of manifest.cdm.json file for ADLS Gen2 connector in Power BI

### ISSUE THREAD

**Issue by deepspraj** [microsoft/CDM#338]
When trying to connect Power BI to CDM container, it supports connection for model.json file only when the connector will support manifest.cdm.json file ?
[Reference](https://powerbi.microsoft.com/es-es/blog/power-bi-dataflows-and-azure-data-lake-storage-gen2-integration-preview/#:~:text=Adding%20a%20CDM%20folder%20to,you%20would%20for%20any%20dataflow.) on how to connect to CDM container to Power BI.

**Comment by victor-gutemberg** [comment]
hello @deepspraj,

this repo is for the CDM SDK, we don't own the Power BI CDM connector. 
Please use the Power BI channels to ask this question.
