### ISSUE TITLE
Python samples to read manifest file

### ISSUE THREAD

**Issue by hurtn** [microsoft/CDM#344]
Hello [the documentation](https://learn.microsoft.com/en-us/common-data-model/sdk/from-modeljson-to-the-future#using-the-common-data-model-sdk-with-modeljson-files) claims it should be possible to use the SDK for python however I don't see any samples or documentation to support this. Could you please advise?

**Comment by mfriscia7** [comment]
Hi @hurtn, your link referred to the 'Using the Common Data Model SDK with model.json files' section. Though we do not have a sample doing those exact steps, we do have a Python sample that shows how to read a model.json file (and then saves it): https://github.com/microsoft/CDM/blob/master/samples/4-read-local-save-adls/code-python/main.py

API documentation can be found [here](https://learn.microsoft.com/en-us/common-data-model/1.0om/api-reference/api-reference). Unfortunately, it is only in C# but the apis are the same in Python (other than following naming conventions, i.e. FetchObjectAsync in C# is fetch_object_async in Python).

I hope that helps!

**Comment by dingbx** [comment]
Closing this issue. Please reopen if you need any further help.
