### ISSUE TITLE
Python ADLSAdapter hostname end backslash

### ISSUE THREAD

**Issue by dim123dim123** [microsoft/CDM#345]
Hi when we just copy endpoint from AZDL endpoints page , it come with last symbols backslash "/" 
in class  ADLSAdapter we got error message "Could not read .. file " because 
function create_adapter_path 
line 162 : 
return 'https://' + self._remove_protocol_from_hostname(self.hostname) + self._get_escaped_root() + self._escape_path(formatted_corpus_path)

It can be fixed :

function _remove_protocol_from_hostname - if last symbrol is "/" remove it

**Comment by mfriscia7** [comment]
Hi @dim123dim123, thank you for the heads up. We will make that fix and let you know here when that happens. In the meantime, make sure to remove the trailing backslash character before making that call.

**Comment by Venkata1920** [comment]
Hi @dim123dim123, we have created a backlog task to address this issue. Please use the suggested alternative till the backlog task is prioritized and fixed.
