### ISSUE TITLE
Gender fields are out of sync across CDM and should include nonbinary/non-binary

### ISSUE THREAD

**Issue by lee0c** [microsoft/CDM#349]
As there are forms of legal ID with 'X' gender markers, the CDM should allow for 'nonbinary' or 'non-binary' as a gender option to align correctly.

I have documented all of the different files which contain gender data that I can find. I would love to PR changes to these files, but want to double check that a) I have all the relevant files and b) that this PR would be accepted.

Here's the files and which options they allow for gender. Ideally, this would be standardized across all files, but I think that might be a lost cause as some of these have options which are direct alternatives to others.

| File/line | Male | Female | Non-binary | Other | Unknown | Unidentified | Choose not to identify | Prefer not to say | Item |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| [applicationCommon/Contact](https://github.com/microsoft/CDM/blob/master/schemaDocuments/core/applicationCommon/Contact.cdm.json#L1823) | X | X |  |  |  |  |  |  |  |
| [customerInsights/CustomerProfile](https://github.com/microsoft/CDM/blob/master/schemaDocuments/core/applicationCommon/foundationCommon/crmCommon/solutions/customerInsights/CustomerProfile.cdm.json#L2165) | X | X |  |  |  | X | X |  |  |
| [electronicMedicalRecords/Contact](https://github.com/microsoft/CDM/blob/master/schemaDocuments/core/applicationCommon/foundationCommon/crmCommon/accelerators/healthCare/electronicMedicalRecords/Contact.cdm.json#L218) | X | X |  | X | X |  |  |  | X |
| [[samples]electronicMedicalRecords/Contact](https://github.com/microsoft/CDM/blob/master/samples/example-public-standards/core/applicationCommon/foundationCommon/crmCommon/accelerators/healthCare/electronicMedicalRecords/Contact.cdm.json#L34) | X | X |  | X | X |  |  |  | X |
| [electronicMedicalRecords/FamilyMemberHistory](https://github.com/microsoft/CDM/blob/master/schemaDocuments/core/applicationCommon/foundationCommon/crmCommon/accelerators/healthCare/electronicMedicalRecords/FamilyMemberHistory.cdm.json#L1495) | X | X |  | X | X |  |  |  |  |
| [clinicalCore/FamilyMemberHistory](https://github.com/microsoft/CDM/blob/master/schemaDocuments/Healthcare/Clinical/ClinicalCore/FamilyMemberHistory.cdm.json#L1566) | X | X |  | X | X |  |  |  |  |
| [loanApplicationContact](https://github.com/microsoft/CDM/blob/master/schemaDocuments/FinancialServices/LoanOnboardingDataModel/Loanapplicationcontact.cdm.json#L2029) | X | X | X |  |  |  |  | X |  |
| [retailBankingCoreDataModel/GlobalOptionSets](https://github.com/microsoft/CDM/blob/master/schemaDocuments/FinancialServices/RetailBankingCoreDataModel/Globaloptionsets.cdm.json#L9391) | X | X | X |  |  |  |  | X |  |

**Comment by dingbx** [comment]
Hi Lee,

The schema can't be updated by us, it is defined by the Dataverse solution provider. We have created a task to track this issue and will reach out to Dataverse to update the schema. We can't merge the PR directly from GitHub, but please feel free to send the PR and we will use it as a reference.

Thanks,
Yijing

**Comment by lee0c** [comment]
Closing as this needs to be handled at other levels.
