### ISSUE TITLE
Avro Schema Generators

### ISSUE THREAD

**Issue by ajithk** [microsoft/CDM#35]
We should be able to generate Open API and Avro Schema from CDM , so that BigData Storage and Processing using Avro and exposing or sharing the data via API using OpenAPI can be achieved.

**Comment by zolyfarkas** [comment]
Once generated, avro schema's could be published (along with language bindings and documentation) to maven repositories, allowing easy re-use, composition, etc...

some examples of avro schemas: 

  https://github.com/zolyfarkas/core-schema / https://zolyfarkas.github.io/core-schema
  https://github.com/zolyfarkas/fred-schema / https://zolyfarkas.github.io/fred-schema
  https://github.com/zolyfarkas/avro-schema-examples
