### ISSUE TITLE
CDM Usage outside Microsoft Apps

### ISSUE THREAD

**Issue by lgltchguy** [microsoft/CDM#350]
Hello all, 

I wanted to know, if the CDM is also designed to be integrated with non Microsoft apps and programs. 

Is the CDM (the entities, its definitions and structure) designed to be used in other products explicitly not built using Microsoft services?

As far as I understand the Microsoft CDM FAQ, this is one of the central purposes of the CDM. The CDM is opensource and intended to be used in as many products as possible, even outside the Microsoftcosmos.

Or am I wrong and the CDM is designed to be used only by Microsoft services (and with services created by Microsoft platforms)?

Thanks a lot for your help!

**Comment by mfriscia7** [comment]
Hi @lgltchguy,

What you are saying is correct, it is not designed to be only used by Microsoft services.

The [schema documents found in this repo](https://github.com/microsoft/CDM/tree/master/schemaDocuments) are based on entities found in Microsoft Dataverse, so those schemas are helpful for integration there. However, you can use the CDM SDK to create your own CDM schemas that have nothing to do with that and are completely separate from any Microsoft services.
