### ISSUE TITLE
Which CDM entity can be used for Product Attribute/Dimension/Batch Attribute from D365?

### ISSUE THREAD

**Issue by banluo-ms** [microsoft/CDM#351]
Hello all,

I'm from Dynamics 365 SCM team. We are working on a new service to integrate product detail from Dynamics 365 SCM to CDM.
We need to integrate Product Attribute/Product Dimension/Batch Attribute, but cannot found proper entity in CDM navigator (https://microsoft.github.io/CDM/SchemaViz.html).

Could you please advise if there is any CDM entity is designed for these master data of product?

Thank you,
Ban

**Comment by Venkata1920** [comment]
Hi @banluo-ms , there may not be an entity that matches your requirements. But, you are free to generate CDM schema for entities in your solutions.
