### ISSUE TITLE
How to use the python CDM objectmodel

### ISSUE THREAD

**Issue by akshayin** [microsoft/CDM#352]
I have installed the python CDM using the README.
I need to know how to use this python CDM in order to get all the object model and their Entity and relationship.
How to use the json file to fetch the entities, which object model belong to which json files?
Is there any sample code and instructions for it.

**Comment by Venkata1920** [comment]
Hi @akshayin , you can find some samples under the sample folder. Ex: https://github.com/microsoft/CDM/tree/master/samples/2-create-manifest/code-python
