### ISSUE TITLE
name of standard trait is automatically prefixed with 'cdm:/primitives.cdm.json/'

### ISSUE THREAD

**Issue by dgcaron** [microsoft/CDM#353]
i am trying to create a  common datsmodel using the typescript sdk but i am having trouble adding standard traits to my data model. 

when i use 

```

const newTrait: CdmTraitReference = this.corpus.MakeObject(cdmObjectType.traitRef, 'is.sensitive', false);
--
attribute.appliedTraits.push(newTrait, false);
```

the saved document contains 
```
{
                    "name": "SSN",
                    "appliedTraits": [
                        {
                            "corpusPath": "cdm:/primitives.cdm.json/is.sensitive",
                            "identifier": "is.sensitive"
                        }
                    ],
                    "dataFormat": "String"
                },
```

whereas  i expect it to be
```
{
                    "name": "SSN",
                    "appliedTraits": [
                        "is.sensitive"
                    ],
                    "dataFormat": "String"
                },
```

this behaviour goes away if i remove the primitives / foundations import from the entity document.

**Comment by Venkata1920** [comment]
Hi @dgcaron , could you provide a sample of your code that saves the file in this schema?

**Comment by dgcaron** [comment]
Sure, I am on a short break right now but will provide a gist of the code at the end of the week.

**Comment by dgcaron** [comment]
hi, i have created a repro with a test here where you can run the code using an azure default credential. 

[cdm-trait-gist](https://github.com/dgcaron/cdm-trait-gist)

this code saves the manifest and the entity docs directly to adls gen2

**Comment by mfriscia7** [comment]
hi, I see the issue is here: https://github.com/dgcaron/cdm-trait-gist/blob/b58681a910f9c28ecc23ef3fe3db396e4084113c/src/index.ts#L183

If you remove the copyOptions and call SaveAsAsync with only the first two parameters, it should work as expected. I think that 'StringRefs' parameter is poorly named as it does not create string references if set to true (it is false by default). The default copyOptions should be what you are looking for.

**Comment by dgcaron** [comment]
yes, that fixes the issue. thanks for taking the time to check this out!
