### ISSUE TITLE
CDMPoster_a3 has a misspelling

### ISSUE THREAD

**Issue by ctkdev** [microsoft/CDM#355]
practitioner != practicioner
https://github.com/Microsoft/CDM/blob/master/docs/CDMPoster_a3.pdf

**Comment by dingbx** [comment]
Hi, thanks for reporting that. I've reached out to the person who can fix that.

**Comment by dingbx** [comment]
Hi,

This issue is now fixed within the PR https://github.com/microsoft/CDM/pull/356.

Thanks,
Yijing
