### ISSUE TITLE
How to create our own data model in CDM

### ISSUE THREAD

**Issue by sing-ideas** [microsoft/CDM#359]
Looking for proper guidance and training on this CDM for my developer. How to get trained end-2-end on creating required files for CDM.

**Comment by Venkata1920** [comment]
Hi @sing-ideas, there are quite a lot of documentation on CDM. Please start [here](https://learn.microsoft.com/en-us/common-data-model/) if you would like to know more and learn about CDM and its scope. If you already know about CDM and the SDK, then please refer [here](https://learn.microsoft.com/en-us/common-data-model/creating-schemas) for creating schema documents for the entities and generate manifests.

**Comment by sing-ideas** [comment]
Yes, we saw that documentations and exploring for some time. Is there any way to get trained or is there any forum specific to developing CDM for an ISV (Independent Software Vendor), we understood the importance of CDM, it is wonderful and started using Power Apps Data Verse, but looking to create an independent application that runs independently and integrates with Power Apps. Other than the document links is there a way to get trained on this.
