### ISSUE TITLE
TypeScript NPM Package?

### ISSUE THREAD

**Issue by v-jaebe** [Microsoft/CDM#36]
I see that the `Tools/cdm-types/cdm-types.ts` file exists, but including it in a project that requires stricter linting rules leads to compilation issues due to the loose use of "any".

Is there an NPM package published with the type definitions? If so, can you provide the package name here and somewhere prevalent in the documents?

If not, can you publish it up ASAP to help drive adoption?

**Comment by JeffBern** [comment]
npm package was published recently. thanks for the nudge :)

**Comment by jacob-ebey** [comment]
Thanks @JeffBern
