### ISSUE TITLE
Search is limited to Entity only, it should also match on attribtues

### ISSUE THREAD

**Issue by nssidhu** [microsoft/CDM#366]
Currently the Search text only searches for Entities that match for the keyword.

It should also do match on attributes and highlight all the entities that match on attributes.

**Comment by nssidhu** [comment]
I am talking about searching using this tool
https://microsoft.github.io/CDM/SchemaViz.html?initialManifest=standards.manifest.cdm.json&simpleChrome=true 

there should be an option to select whether we want to search on entity only or attributes only or both

**Comment by sing-ideas** [comment]
This is a must required feature, how to search attributes, whether they already available or not.

**Comment by mafrisci** [comment]
We are currently not actively updating the tool. If this is a feature you would like, feel free to fork the repo and makes the changes.
