### ISSUE TITLE
Converting JSON schema to ER Diagrams

### ISSUE THREAD

**Issue by smita2006** [microsoft/CDM#367]
I have a couple of questions:

1. Is there a way we can directly convert these common data model json schemas to ER diagrams? If yes then is it possible in MS Visio? 

As per my findings so far MS Visio supports importing the following data sources:
**Excel workbook, Access database, SQL Server database, SharePoint list, OLEDB source, or an ODBC source**

so do we have to first convert the json into an excel workbook and then try importing the workbook to generate the ER diagram?

2. Also because these jsons are highly nested so while trying to convert it into excel workbook either a lot of column values(as imported from the json file) gets repeated or they appear as unnecessary from a DB schema(which we are trying to depict in the ER diagram) point of view. How to deal with that and get a precise schema sufficient enough to create the ER diagram?

**Comment by sing-ideas** [comment]
Having an Entity Relationship diagram will certainly help new developers to understand such important concept of CDM. This will be very use for us too. Do let us know on how to get ER diagram in any tools.

**Comment by Olofgo** [comment]
This would be really usefull, some updates?

**Comment by miroslavplese** [comment]
Thanks for reaching out - we don't have any tools available today to convert CDM entity schema JSONs to an ER diagram. Our advice for you is to perform resolve operation on all the entities which will remove any nesting/referencing that currently exists in the logical schema (example of entity resolving can be found in the SDK samples). Once this is done, you can code a new utility that will turn the resolved schema into Excel workbooks and then import that into an ER tool.

**Comment by sing-ideas** [comment]
How do we get proper training on Microsoft CDM operations/projections? Is there any community to discuss or clarify doubts for our young developers?

**Comment by Olofgo** [comment]
As I can see, the relations are not visible within the "Operations" area in CDM inside https://microsoft.github.io/CDM/SchemaViz.html.

Is that correct or am I missing something?

**Comment by Olofgo** [comment]
What is the difference between "Entities" and "Tables" under OperationsCommon?

I understand that Entities is conceptual and that Tables are Physical but can you still use both cstegories as a standard Data Model?

**Comment by mafrisci** [comment]
> What is the difference between "Entities" and "Tables" under OperationsCommon?
> 
> I understand that Entities is conceptual and that Tables are Physical but can you still use both cstegories as a standard Data Model?

In Finance and Operations there is a difference between a Table (which is pretty close to 1:1 with a SQL table) and an Entity (which behind the scenes is a SQL view that wraps one or more tables, or even other entities and views).
