### ISSUE TITLE
Error while loading the .sln file of the CDM Samples

### ISSUE THREAD

**Issue by sing-ideas** [microsoft/CDM#371]
Hi,
We are getting these error message, when we tried to open the .sln file of
How to use samples? 1-read-manifest

Last month in Nov 2023 it was working?

---------------------**************************------------------------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1105	Unable to find project information for 'C:\Users\SingaraveluSStackRad\source\repos\Github\Microsoft.CDM\objectModel\CSharp\Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards\Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.	Microsoft.CommonDataModel.ObjectModel	C:\Users\SingaraveluSStackRad\source\repos\Github\Microsoft.CDM\objectModel\CSharp\Microsoft.CommonDataModel.ObjectModel\Microsoft.CommonDataModel.ObjectModel.csproj	1	
---------------------**************************------------------------------------

![CDM Error Mssg - Samples - 1-read-manifest](https://github.com/microsoft/CDM/assets/34727666/9ef7c88c-fa4c-47ab-b7c8-628743b63aaf)

```[tasklist]
### Tasks
```

![CDM Error Mssg - Samples - 1-read-manifest - screenshot2](https://github.com/microsoft/CDM/assets/34727666/ce933e6e-f752-4b01-b000-ada030704d56)

```[tasklist]
### Tasks
```

**Comment by sing-ideas** [comment]
.Net Runtime encountered the below error, how to fix this?

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0006?f1url=%3FappId%3Droslyn%26k%3Dk(CS0006)

"Failed to create CoreCLR, HRESULT: 0x80070057" indicates that the .NET runtime encountered a problem while trying to initialize itself when running your application read-manifest.exe.

**Comment by mafrisci** [comment]
This can be fixed by manually adding the Cdmstandards project file to the solution: https://github.com/microsoft/CDM/blob/master/objectModel/CSharp/Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards/Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards.csproj

We will also fix this issue in the next release.
