### ISSUE TITLE
Encountering Errors with ADLS Adapter in Azure Functions

### ISSUE THREAD

**Issue by tvanderv92** [microsoft/CDM#377]
**Environment**

Azure Functions (Python)
Azure Identity
Microsoft Common Data Model SDK
Azure Data Lake Storage Gen2

**Issue Description**
I'm attempting to fetch a manifest file (model.json) from an Azure Data Lake Storage Gen2 account using the ADLS Adapter in the Microsoft CDM SDK within an Azure Function. However, I'm encountering an error indicating a failure to read from the specified path.

**Error message**
`PersistenceLayer | Could not read '/model.json' from the 'adls' namespace. Reason ''str' object has no attribute 'args'' | _load_document_from_path_async | /model.json
[2024-04-02T09:49:06.132Z] 2024-04-02 11:49:06,130      ERROR   logger.py:87    _log    PersistenceLayer | Could not read '/model.json' from the 'adls' namespace. Reason ''str' object has no attribute 'args'' | _load_document_from_path_async | /model.json`

**Code**
```
import logging
import re
import azure.functions as func
import asyncio
from azure.functions import Blueprint
from azure.identity.aio import DefaultAzureCredential
from cdm.enums import CdmObjectType
from cdm.objectmodel import CdmCorpusDefinition
from cdm.storage.adls import ADLSAdapter

metadata_bp = Blueprint()

async def fetch_manifest(corpus):
    try:
        manifest_path = 'adls:/model.json'
        _manifest = await corpus.fetch_object_async(manifest_path)
        if _manifest:
            print("Successfully fetched the manifest file.")
            return True
    except Exception as e:
        print(f"Failed to fetch the manifest file: {e}")
        return False

@metadata_bp.route('fetch_metadata', auth_level=func.AuthLevel.ANONYMOUS, methods=['POST'])
async def fetch_metadata(req: func.HttpRequest) -> func.HttpResponse:
    credentials = DefaultAzureCredential()
    corpus = CdmCorpusDefinition()

    corpus.storage.mount('adls', ADLSAdapter(
        root='/<container/filesystem>',
        hostname='<storage-account-name>.dfs.core.windows.net',
        tenant='<tenant-id>',
        token_provider=credentials
    ))

    await fetch_manifest(corpus=corpus)

    return func.HttpResponse("Fetched metadata")
```

**Expected Behavior**
The function should fetch the manifest file without errors

**Actual Behavior**
The function logs an error about failing to read the manifest file

**Steps to Reproduce**
1. Setup an Azure Function(Python) using the V2 Model(using blueprints)
2. Ensure DefaultAzureCredentials() is working(az login etc or other methods)
3. Debug function in vscode

**Additional Context**
I've looked at the class functions(inside the cdm packages) and I cannot find any reason why it should not work(as the functions accept strings as input).

requirements.txt:

azure-functions==1.18
azure-storage-file-datalake==12.14.0
azure-core==1.30.1
azure-identity==1.15.0
azure-mgmt-sql==3.0.1
pyspark==3.5.1
aiohttp==3.9.3
requests==2.31.0
nest-asyncio==1.6.0
commondatamodel-objectmodel==1.7.5
tenacity==8.2.3

**Comment by tvanderv92** [comment]
fixed it by using a custom Token Provider

**Comment by mafrisci** [comment]
Hello @tvanderv92, as you found, we do not support default authentication in Azure Functions, you must use a custom TokenProvider instead (as you found out).

**Comment by sing-ideas** [comment]
Is there any community for Microsoft CDM adoption along with DataVerse?
