### ISSUE TITLE
Standard Manifest Names Missing

### ISSUE THREAD

**Issue by workflowanalytics** [microsoft/CDM#380]
Porting over to 1.7.6 and had issues loading the manifest files in the following folders:
Sustainability
CustomerInsightsJourneys
customerInsights

Manifest files may be present but they either have a versioned name or use a default prefix.

I'm using the June 6th zip file download.

Thanks

**Comment by mafrisci** [comment]
Hi @workflowanalytics.

For the Sustainability folder, structure of those files has changed, and that is why you do not see the unversioned files at the root level. Those can be found within the subfolders underneath Sustainability.

For the CustomerInsightsJourneys folder, the default.manifest.cdm.json file should be the correct one, is there an issue with the manifest having that name?

And which folder are you referring to? [This one](https://github.com/microsoft/CDM/tree/master/schemaDocuments/core/applicationCommon/foundationCommon/crmCommon/solutions/customerInsights)? If so, there is a customerInsights.manifest.cdm.json file that should be what you are looking for.
