### ISSUE TITLE
How to adopt Microsoft Dynamic Link Library (DLL)

### ISSUE THREAD

**Issue by sing-ideas** [microsoft/CDM#387]
Our developer suggesting adopting the Microsoft Dynamic Link Library (DLL) instead of parsing the .json files.

Can you give inputs on this, whether Microsoft CDM SDK and CDM APIs will be compatible?

Will your team adopt this Microsoft Dynamic Link Library (DLL) in the Microsoft CDM SDK?

When is your next release on Microsoft CDM Repo?

**Comment by mafrisci** [comment]
Can you explain what you mean by this? The default behavior of the SDK is to read the schema files from the CdmStandards project, which should be compiled into a dll file

**Comment by sing-ideas** [comment]
Checking with our developer. allow us little time.

**Comment by sing-ideas** [comment]
Thanks for your reply

The previous response clarifies how the SDK integrates its functions. 

However, my original question focused on the feasibility of creating database tables directly from the cdm.json files.
