### ISSUE TITLE
NU1105 : Unable to find project information #2

### ISSUE THREAD

**Issue by sing-ideas** [microsoft/CDM#388]
What is the correct fix?

Our team have narrowed down to, can we try the below fix?
We tried...
1. Run msbuild /t:Rebuild .
2. Run dotnet restore (project name) ex - dotnet restore read-manifest .

Not sure this is a correct fix. Need your team inputs. 

Below is the issue...
Our developer getting error message
Using Visual Studio Pro.

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	NU1105	Unable to find project information for 'C:\Users\mylai\Downloads\CDM-master\CDM-master\objectModel\CSharp\Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards\Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.	Microsoft.CommonDataModel.ObjectModel (net462), Microsoft.CommonDataModel.ObjectModel (netstandard2.0)	C:\Users\mylai\Downloads\CDM-master\CDM-master\objectModel\CSharp\Microsoft.CommonDataModel.ObjectModel\Microsoft.CommonDataModel.ObjectModel.csproj	1

![Error Message](https://github.com/user-attachments/assets/c69d8406-5474-4df0-861e-8dbcd19c31e7)

**Comment by mafrisci** [comment]
Hello @sing-ideas , it looks like the solution does not contain the CdmStandards project. We can make a fix on our side, in the meantime you can add the following project as a Project Dependency: [https://github.com/microsoft/CDM/blob/master/objectModel/CSharp/Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards/Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards.csproj](https://github.com/microsoft/CDM/blob/master/objectModel/CSharp/Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards/Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards.csproj)

**Comment by sing-ideas** [comment]
Thanks, will inform developer.

> Hello @sing-ideas , it looks like the solution does not contain the CdmStandards project. We can make a fix on our side, in the meantime you can add the following project as a Project Dependency: [https://github.com/microsoft/CDM/blob/master/objectModel/CSharp/Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards/Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards.csproj](https://github.com/microsoft/CDM/blob/master/objectModel/CSharp/Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards/Microsoft.CommonDataModel.ObjectModel.Adapter.CdmStandards.csproj)
