### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by workflowanalytics** [microsoft/CDM#389]
In reviewing the most recent download of CDM, labeled as version 1.76, I noticed that a number of classes are marked as 'Deprecated in version 3.0'. Are there different versioning systems or is 1.76 'on the road' to 3.0?

**Comment by mafrisci** [comment]
The description you see referring to "version 3.0" comes from descriptions in the Dynamics365 entities where these entities originate from. They do not refer to the CDM version, so the description can safely be ignored.
