### ISSUE TITLE
[question] Resource type

### ISSUE THREAD

**Issue by eliebe-5** [microsoft/CDM#46]
We think of the resource type as being representative of everything inbetween human resources to licenses, repositories, or servers.

How come the resource type is under service, and isn't a common to be extended? Is our way of thinking not the CDM-way?

**Comment by JeffBern** [comment]
I think you are right. For the CRM derived entities, the placement into this folder hierarchy was determined less by the "logical" meaning or use of the entity and more by the dynamics solutions that create the entities and the dependencies between these solutions. The reason for this choice was to group together the entities that a customer is likely find given the solutions they have installed. The Resource entity is installed by the Service solution.  Make sense?
