### ISSUE TITLE
version question

### ISSUE THREAD

**Issue by justyu** [Microsoft/CDM#52]
Hi, 
I am new to CDM, and I have a question about the cdm schedma version.

In this page https://microsoft.github.io/CDM/  when I click "Currency" under applicationCommon in the left, I can see the version of the "Currency" entity is "0.8.1" as below:

Entity | Currency
-- | --
displayName | Currency
description | Currency in which a financial transaction is carried out.
version | 0.8.1
cdmSchemas | [   "/core/applicationCommon/Currency.cdm.json/Currency/hasAttributes/attributesAddedAtThisScope" ]
sourceName | TransactionCurrency

But when I download the related cdm json file(https://raw.githubusercontent.com/Microsoft/CDM/master/schemaDocuments/core/applicationCommon/Currency.cdm.json), which I get it from the broswer log, I see the version info : jsonSchemaSemanticVersion: "0.7.0" and I can NOT find the "0.8.1" in this json file.

Can you tell me what is the difference between this two version number?
And how can I get the displayed version(0.8.1) from the json file?

Thanks very much.

**Comment by justyu** [comment]
Hi JeffBern, 
Thanks for your reply.
But I am still confused, You mentioned now it is .7, while why I can see the following info below which shows 0.8.1? which I should believe it the correct version?

Entity | Currency
-- | --
displayName | Currency
description | Currency in which a financial transaction is carried out.
version | 0.8.1
cdmSchemas | [ "/core/applicationCommon/Currency.cdm.json/Currency/hasAttributes/attributesAddedAtThisScope" ]
sourceName | TransactionCurrency

We want to track the entity properties with version through our API, but I don't know how to get the correct version for the CDM schema.

Thanks.

**Comment by justyu** [comment]
anyone can help?

**Comment by JeffBern** [comment]
The current version of the 'Currency' entity (that is, the attributes and traits that describe Currency) is 0.8.1
The version of the json schema with which the entity is described and the typescript object model code that understands that schema is 0.7.
There are two ways to get the 0.8.1 version number from the entity:
1. if NOT using the typescript OM. If the entity has a specific 'exhibitedTrait' called  'is.CDM.entityVersion' is will also have a property called 'version' and these will hold the version number (this is true on the files that have a version number in their file names). If the entity has no explicit version set, then it is the 'most current' version and uses the default entity version number which can be found as the defaultValue property in the definition of the 'is.CDM.entityVersion' trait in foundations.cdm.json.
2. if using the OM, just read the 'version' property of the entity.

**Comment by justyu** [comment]
Got it,
One more question, what is OM short for?

**Comment by theresapalmer** [comment]
Good question, OM stands for object model. Based on Jeff's response for the versioning I'll close this item but please feel free to create another or reopen if you have other questions!
