### ISSUE TITLE
Broken links for AcademicPeriod and its details

### ISSUE THREAD

**Issue by emres** [microsoft/CDM#55]
The links for AcademicPeriod and AcademicPeriodDetails are broken, the following links that exist in `README.md` give `404` error:

- https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/entities/mshied_academicperiod

- https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/entities/mshied_academicperioddetails

**Comment by theresapalmer** [comment]
Thanks @emres - we're aware of the issue and are tracking new documentation that these links will point to. The fix should be available in the next few weeks, I'll leave this issue open until it's published!
