### ISSUE TITLE
Visual Entity Navigator gives a TypeError when Load from Github! is clicked

### ISSUE THREAD

**Issue by emres** [Microsoft/CDM#56]
[Visual Entity Navigator](https://microsoft.github.io/CDM/) gives a TypeError when "Load from Github!" button is clicked:

```
TypeError: NetworkError when attempting to fetch resource.
/core/applicationCommon/foundationCommon/crmCommon/solutions/portals/AdPlacement.cdm.json
```

**Comment by theresapalmer** [comment]
Hi @emres - is it possible you have an ad blocker on in your browser? We've seen this previously, due to the name of the entity some ad blockers will prevent it from loading. Let me know if you disable the ad blocker and still have the issue.

**Comment by emres** [comment]
Indeed! Just tried it with a browser that didn't have any ad blockers, and this time it worked like a charm! Could be good if you put this as an explanation somewhere close to the Visual Entity Navigator link. 

Thanks for your quick and to-the-point support again!
