### ISSUE TITLE
Best Practice for reference fields

### ISSUE THREAD

**Issue by chall-bhs** [microsoft/CDM#59]
When looking over the schema I have found a number of fields which have as their data type, a reference to a field on another entity. Is there an established BP for how to cope with this, if the goal is to retrieve the data type for that field?

**Comment by victor-gutemberg** [comment]
Hello @chall-bhs,

It's been a while that you opened this ticket, but if you still have this question please go ahead and check our documentation about [`Entity Attributes`](https://docs.microsoft.com/en-us/common-data-model/sdk/logical-definitions#using-an-entity-as-the-type-of-an-attribute). That's the formal name of the type of attribute you're describing.
