### ISSUE TITLE
Clarification on File Pointers

### ISSUE THREAD

**Issue by noodlescb** [microsoft/CDM#60]
From the documentation on this page : https://docs.microsoft.com/en-us/common-data-model/data-lake

> The model.json metadata file provides pointers to the entity data files throughout the CDM folder.

This seems to imply that the model.json file would need to contain a pointer to every file in the tree. Is it every file or every folder? The examples in the documentation don't show a long list of files.

If it is every file, what is the vision for delta files? If I send a file with the changes for the last 24 hours is the expectation that I update the model.json to have an explicit link to the new file? What if someone deletes any file in the past? 

Thanks!
Caleb

**Comment by theresapalmer** [comment]
Hi Caleb - yes today the model.json file would contain a pointer to every data file that should be included in the model. We are looking at an improvement in this area to allow partners to define a pattern of data files that should be included (i.e. everything in this subfolder, everything that matches *.cdmdata.csv, etc.) to allow a producer to add more data files without having to update the model.json file each time. 

For the delta file scenario, could you describe more how the file would indicate the changes and what you'd expect from a consumer of your model.json? Today the expectation is that the producer updates the model.json to indicate which data files a consumer should read and that the consumer can read the files as-is. The specification intends to make the consumption as simple as possible, as in this type of ecosystem there are typically many more consumers than producers.
