### ISSUE TITLE
Model Constraints Enforcement

### ISSUE THREAD

**Issue by estemba** [microsoft/CDM#64]

**Comment by estemba** [comment]
I am interested to know if the model.json schematization is used also to enforce that the underlying data is compliant. From a quick read it seems to provide valuable metadata complement to the underlying information, not clear if it activates any constraints on data types ,values etc.. If I specify that a field in an custom entity is a date, would I be able to able to have in the underlying CSVs a field of a different type or is there a way to use the metadata to enforce consistency?

**Comment by victor-gutemberg** [comment]
Hello @estebam,

there is no enforcement from the CDM SDK side, but the expectation is that the data writer is following what they're describing as metadata. It would be a very big effort to support this in the SDK since there are many different data sources that operate in different ways.
