### ISSUE TITLE
How to install CDM folders in ADLSg2

### ISSUE THREAD

**Issue by jainayush007** [microsoft/CDM#66]

**Comment by oovanesy** [comment]
Hello,
CDM folders - data in CSV files and the metadata file(s) can be created, for example, by Power BI data flows using Map to standard feature, or using Azure Data Factory functionality we've announced at Ignite, or Export data from Dynamics - also announced at Ignite. You can also write custom code to load data into the lake in CDM folders. Please watch https://myignite.techcommunity.microsoft.com/videos/66467 presentation for reference

**Comment by josiahvinson** [comment]
@oovanesy the session you linked to talks about Azure subscription management. Were you referring to this session? https://myignite.techcommunity.microsoft.com/sessions/83511
