### ISSUE TITLE
Link between schemaDocuments and model.json

### ISSUE THREAD

**Issue by KevinMcDonnell-BC** [microsoft/CDM#67]
Is there a way to generate the model.json from the set of schemaDocuments? The model.json schema seems like it has less definition but is used for Data Lake. 

Ultimately, I'd like to be able to create a set of classes in C# as well as the Dynamics and Power BI implementations so looking in to whether it is based to define extensions in the model.json format or the full schema (my preference at the moment).

Thanks!

**Comment by victor-gutemberg** [comment]
Hello Kevin,

My recommendation is that you use the SDK to read and write either the ".cdm.json" format or "model.json" format. Both can be manipulated using the same set of API's but persisted to different file formats. You can take a look at [this sample](https://github.com/microsoft/CDM/tree/master/samples/1-read-manifest/code-cs) to understand better that scenario. For example, you can load the document you want from the `schemaDocuments` and save it as a model.json.

As a side note, model.json is in deprecation path and its use should be avoided. You can read more about this on our [`From model.json to the future`](https://docs.microsoft.com/en-us/common-data-model/sdk/from-modeljson-to-the-future) article.
