### ISSUE TITLE
Visual Entity Navigator won't load (offline) GitHub source files

### ISSUE THREAD

**Issue by jschof** [microsoft/CDM#68]
I wanted to download the source files, modify them and then load them back for testing purposes but when I do so it starts loading and then simply hangs with the message "Loading and resolving entity documents, please wait...".

It is possible to get the source files used when you click on "Load from Github!" or fix the source files in Github so they can be loaded from the desktop and get the same results using either method?

**Comment by oovanesy** [comment]
@jschof, Hi, and thanks for the interest in CDM. Current version of the Entity Navigator does not support "load from local files" function. We are working on improving this experience and support this functionality

**Comment by oovanesy** [comment]
@jschof can you please tell us what files are you trying to load with the navigator? e.g. custom built, copies from GitHub?

**Comment by jschof** [comment]
I tried to load the files from the schemaDocuments folder. If the results were the same as when you click on "Load from Github!" then my intent was to start modifying the source files to create my own custom build.

What I did not know at the time was that the GitHub files also contained the Entity Navigator source files (in the docs folder) and that there were many hard-coded references in the index.html file which make the exercise non-trivial.

I did manage to create my own model that works well except if you look under the covers at the Status tab there are errors for objects that I am not using (I.e. have removed):

> resolving references...
> unable to resolve the reference 'User' to a known object
> unable to resolve the reference 'Team' to a known object
> unable to resolve the reference 'User' to a known object
> unable to resolve the reference 'User' to a known object
> unable to resolve the reference 'User' to a known object
> unable to resolve the reference 'User' to a known object
> unable to resolve the reference 'BusinessUnit' to a known object
> unable to resolve the reference 'User' to a known object
> unable to resolve the reference 'Team' to a known object
> unable to resolve the reference 'Activity' to a known object
> unable to resolve the reference 'Contact' to a known object
> unable to resolve the reference 'Account' to a known object


BTW for those looking to so a similar exercise you may want to modify SchemaViz.css to include object property wrapping, much easier / preferable to scrolling.

```
.property_table_detail_value
{
    white-space: pre-wrap;    /* Display formatted definitions*/ 
}
```

**Comment by JeffBern** [comment]
BTW, we are hard at work on a major update to the CDM OM (and navigator as part of that) that will make it possible and much easier to integrate you own folders of content into an overall schema 'corpus'. Stay tuned.

**Comment by sbrown-ai** [comment]
Not sure if this is a resolved issue now for you, but we had the same experience. When we removed the "other versions" (left the un-numbered) versions it worked. Looks like 0.7 is not compatible with the visualizer? Anyway... removing 0.7, 0.8, 0.8.1 we were able to get local files to load.

**Comment by jschof** [comment]
Fixed in Microsoft CDM Release Version Update: 1.0.9

**Comment by Venkata1920** [comment]
Hi @jschof , the "Load from files" option has been working for a while. Please ensure you do remove older versions as suggested by @sbrown-ai as they are old and hence not compatible.
