### ISSUE TITLE
Docs on how to create C# classes

### ISSUE THREAD

**Issue by shaggygi** [microsoft/CDM#69]
Is there any documentation how to create C# interfaces/classes based on CDM?  I'm hoping to create/use a .NET Standard API based on a set of defined entities.

It would be nice to have a core API that includes only the objects defined in CDM.  We could then have separate APIs to reference that API to perform the interaction between data stores/apps.

Any help is appreciated.

**Comment by oovanesy** [comment]
hi, could you please describe what scenario/use you have in mind?

**Comment by shaggygi** [comment]
I might be off in the weeds while trying to understand CDM, but based on docs and blogs I've crossed, I think would help in a project my team is researching.  I like the fact you can define a CDM folder that supposed to include your models (from primitives to complex models to extensions of models). 

So I thought there would be provided APIs/SDKs that could convert the data into C# classes where we could use in apps and against data repos (understanding that would be most likely on us depending SQL, CosmoDB, CSV file, etc.).

For example, if I had a model for a CustomerOrder, I would eventually want to be able to do something like...

```csharp
var customerOrder = new CustomerOrder();
customerOrder.OrderNumber = "1234ABCD";
// other defined properties...
```

One area I wasn't clear on was the Common Data Service.  It appears the CDM folder contains all the data to perform things in data lakes, Azure and such.  If we have the ability to separate just the models, I could see using in various apps including down to Commands, Telemetry, Interfaces as what the [IoT Plug and Play (DTDL)](https://github.com/Azure/IoTPlugandPlay/issues/15) team appears to be doing.

Sorry if not clear enough.  Let me know if I need to provide more details.

**Comment by JasonSowers** [comment]
I have the same question.

**Comment by charbull** [comment]
This is exactly the purpose of OLGA.
https://ecostruxure.github.io/OLGA/

Take an ontology model and generates C#, Java, Python code ...

Take a look
