### ISSUE TITLE
Why include both KbArticle and KnowledgeArticle?

### ISSUE THREAD

**Issue by amervitz** [Microsoft/CDM#7]
Why are there two entities, [KbArticle ](https://github.com/Microsoft/CDM/blob/master/schemaDocuments/core/applicationCommon/KbArticle.cdm.json)and [KnowledgeArticle](https://github.com/Microsoft/CDM/blob/master/schemaDocuments/core/applicationCommon/KnowledgeArticle.cdm.json), effectively representing the same thing? Assuming these are inherited from Dynamics 365, shouldn't only KnowledgeArticle be included since KbArticle is being phased out?

**Comment by JeffBern** [comment]
We published both because although KbArticle is indeed being phased out, but it does still exist and is in use by some application. So, people are likely to run into the entity shape and need to understand the schema outside of Dynamics.
