### ISSUE TITLE
Manufacturing Related Entities

### ISSUE THREAD

**Issue by shaggygi** [microsoft/CDM#70]
Understanding you could build a custom model for Manufacturing using other entities, is there any work going on to build a model with entities specific to Manufacturing?  This would include things like work orders, equipment, testing (UUT - unit under test), inventory quantities, etc.

This would be a big effort when using with IoT and Digital Twin concepts.

I noticed there were [Industry Accelerators](https://docs.microsoft.com/en-us/common-data-model/industry-accelerators).  There seems like there would be one for Manufacturing.

**Comment by oovanesy** [comment]
Hi there, 
we do not have specific timeline for the Industry Accelerator for manufacturing at the moment. and agree with your assessment in re complexity
