### ISSUE TITLE
Common Data Service On-Prem Examples

### ISSUE THREAD

**Issue by shaggygi** [microsoft/CDM#72]
There are cases when we would like to use the CDM with on-prem data sources (e.g. SQL server, etc.) without relying on Azure.  Are there examples how to create .NET APIs to connect with an on-prem data source using Common Data Service connection?

**Comment by JeffBern** [comment]
This is not the right place for this question to be honest, this repo is about describing metadata, most of which happens to come from CDS. I have seen lots of .NET sdk examples for working with dynamics XRM systems. this might give you a good hook into those docs: https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/gg307418%28v%3dcrm.8%29
