### ISSUE TITLE
CDM Roadmap with Milestones

### ISSUE THREAD

**Issue by shaggygi** [microsoft/CDM#74]
There appears to be a [CDM roadmap here](https://docs.microsoft.com/en-us/business-applications-release-notes/april19/cdm-data-integration/planned-features).  It would be nice to add a more detailed plan for work for CDM and how this repo fits in.  This will allow users to understand what's being worked on and more confidence there is a bright future.  I like how other Microsoft teams add milestones (with issues attached to them) along with Projects to see basic status of Not Started, In Progress, and Completed.  If the community had a little more insight, they could possibly help with PRs on bugs, docs, features and defining more data models.

**Comment by JeffBern** [comment]
For context, at the end of last year when CDM got a real engineering team (I didn't count as a real team, I'm ok with that) we moved the active development to an internal git repo and started publishing updates here from time to time. So, this site doesn't reflect the flurry of activity that is actually happening. I agree though that we have been doing a bad job of keeping this site current wrt our plans and timeline. It is good feedback and a good reminder. I will pass this along and make it a priority to be more public about our plans here. thanks

**Comment by shaggygi** [comment]
@JeffBern Thanks for the response and update on the progress.  I'm looking forward to some of the future fruit 😄.  Understanding it's better to hunker down and work on a project without outside interruptions, is there a way the repo (SDKs, APIs, etc.) can be placed back in public view?  We are so enjoying the openness that has been going on with MS these days and I believe the community would be a big help with this, as well.

I would be interesting in helping as 1) there is a research phase going on with my team and believe this tech might be the answer we're looking for and 2) I can see it being very useful with the recent [IoT Plug and Play](https://github.com/Azure/IoTPlugandPlay) announcement and the [.NET IoT](https://github.com/dotnet/iot) repo (where I'm one of the top outside contributors).

Thanks again for any insight and future releases 👍
