### ISSUE TITLE
Process of Proposal

### ISSUE THREAD

**Issue by shaggygi** [microsoft/CDM#76]
What are the procedures and appropriate methods of creating/requesting a proposal for CDM?  For example, if there is a new primitive or attribute that could enhance CDM, what would be required for internal team to review/approve/deny?

**Comment by oovanesy** [comment]
hi. do you mean to suggest a new data type and/or attribute to become part of the CDM standard?

**Comment by shaggygi** [comment]
Yes, while it is little difficult to understand the low-level workings (since it's still new and little APIs/documentation), there are about dozen new primitive data types I can see that would definitely help the standard.

I believe it would be helpful to provide some guidance on what should be expected when a new proposal is provided for team to review.  This could hopefully help the conversion while trying to review/approve/decline during the process.  Other .NET repos usually ask for descriptions, code examples, whys/hows, what does it break, open questions, etc.

Thanks again.

**Comment by Venkata1920** [comment]
Hi @shaggygi , we don't currently have a process for taking direct contributions. However, we do consider improvements and suggestions specifically for bugs and issues. If you do see any improvement opportunities, please feel free to suggest them.
