### ISSUE TITLE
Primitive Data Types

### ISSUE THREAD

**Issue by shaggygi** [microsoft/CDM#77]
Is it expected that primitive data types (from primitives.cdm.json) to always exist for CDM?  Meaning, once defined... they basically will be the "foundation" of how other things are defined?  I'm assuming new data types could be added in future, but there would always be the usual defaults (e.g. Boolean, Integer, etc.).

**Comment by JeffBern** [comment]
the datatype object is actually just an inheritable "bag" of traits. That is, a convenient way of applying some set of traits to an attribute by just naming the type. So, what really matters are the traits that the primitive dataTypes exhibit. Those traits are in the dataFormat group and cover the ideas like int, char, array, date, time, etc.   While CDM would allow for any kind of datatype to be defined and used, there are certain tools and converters that will be looking for the traits that explain the dataFormat and will react to those. So as a short answer to your question, Yes those type should always exist and be the foundations of other types.
