### ISSUE TITLE
Which license applies to cdm.json files?

### ISSUE THREAD

**Issue by amervitz** [Microsoft/CDM#8]
The legal notice states the following:

> Microsoft and any contributors grant you a license to the Microsoft documentation and other content in this repository under the Creative Commons Attribution 4.0 International Public License, see the LICENSE file, and grant you a license to any code in the repository under the MIT License, see the LICENSE-CODE file.

What license do the cdm.json files, e.g. [Contact.cdm.json](https://github.com/Microsoft/CDM/blob/master/schemaDocuments/core/applicationCommon/foundationCommon/crmCommon/Contact.cdm.json), fall under, the CCA license or MIT?

**Comment by RobertBruckner** [comment]
Alan, thanks for your question.  JSON files in this repository are covered under the LICENSE file, i.e. https://github.com/Microsoft/CDM/blob/master/LICENSE
