### ISSUE TITLE
Installing CDM ?

### ISSUE THREAD

**Issue by FrederickLecavalier** [microsoft/CDM#84]
We are looking to build a solution on top of CDM using a PowerApps Plan 2 licence.  Our solution needs to use the opportunity entity.  When looking at the entity in PowerApps, we cannot see the Opportunity entity.  How can we add this entity to our data model ?  Do we need to install something ?

Thanks !

**Comment by oovanesy** [comment]
Hi there, 
There is a reference for the Opportunity entity here https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/opportunity?view=dynamics-ce-odata-9. Does this help?
