### ISSUE TITLE
Missing Entities

### ISSUE THREAD

**Issue by mwc360** [microsoft/CDM#88]
Inventory related Entities like Inventory On Hand, Purchase Orders, etc?

Seems like these are some pretty core entities that are missing.

**Comment by oovanesy** [comment]
Hi there,
Assuming you are referring to Standard Entities published at GitHub that are rooted in D365 definitions.
We will keep growing the list of Standard Entities, however, there are no plans to make it comprehensive for all subject areas. CDM allows creation of custom entities to meet your goals
