### ISSUE TITLE
Versioning of mandatory properties

### ISSUE THREAD

**Issue by amervitz** [Microsoft/CDM#9]
The versioning section states:

> Maintaining forward and backwards compatibility is a key goal of the CDM. Therefore, the CDM uses purely additive versioning, which means any revision of the CDM following an initial release will not:
>
>- Introduce new mandatory properties on existing entities

Should the converse restriction also apply, that a mandatory field cannot be changed to optional?

**Comment by RobertBruckner** [comment]
Alan, thanks for your question. You are right, the converse restriction also applies: a mandatory field cannot be changed to optional.  We'll clarify this in the versioning section.

**Comment by amervitz** [comment]
> Technically though, a mandatory field could be made optional without being a breaking change.

How is that possible? An application "CRM" on schema v1 that expects a mandatory field to be provided on creation would cause an error if it received data from an application "ERP" on schema v2 that didn't provide a value for that field anymore.

**Comment by RobertBruckner** [comment]
If there is a default value defined when the field is made optional.  That said, we expect this to be a rare occurrence.

**Comment by amervitz** [comment]
Please correct me if I'm wrong but not all field types have the concept of a default value.

Also, the revised wording says:

> Introduce new mandatory attributes on previously published entities, or change an optional attribute to be mandatory

Shouldn't this instead be:

> Introduce new mandatory attributes on previously published entities, or change a mandatory attribute to be optional
