### ISSUE TITLE
Custom entities in CDM

### ISSUE THREAD

**Issue by shibanik** [microsoft/CDM#90]
I couldn't find relevant documentation regarding this so posting my questions here:

- How do custom entities work and where are they stored themselves if the corresponding data can be stored in ADLS in CDM folders?
- Can custom entities inherit from standard entities?
- Does batching apply to entity operations? If so, what should be the size of the batch, and what should be the frequency of batching?
- Can the datatype be specified in the schema?

**Comment by oovanesy** [comment]
Hi there,
Entities can be extendend from standard entities
in re batching - CDM is not a deta processing service, ETL tool or query engine. It is the language to describe metadata in a standard way and have ability to add semantics to metadata. CDM does not prescribe data movement. CDM does not cover entity operations, i.e. there are no "actions" defined in CDM
Yes, data types are specificed in standards. You can define a new data type as well
