### ISSUE TITLE
Common Data Model Adoption

### ISSUE THREAD

**Issue by fuchsdaniel** [microsoft/CDM#95]
Hi,

Is it possible to talk with someone from Microsoft regarding this initiative? We're planning a more robust usage, but we need some clarifications regarding the future of the project.

Thanks,

Daniel

**Comment by oovanesy** [comment]
Hi Daniel, thank you for the interest. can you give me a bit more detail on what are you trying to accomplish? And yes, we can definitely connect on the roadmap

**Comment by fuchsdaniel** [comment]
Sorry about the late reply.

Our two main points are: 

>How this model will be expanded since we also have the interest to add our own definitions, focusing on IoT for example? 

>If there is an update version planned, we'd like to understand so we don't focus on creating some "fields" in disagreement about what is being planned. Example: In a Mobile Operator, normally you have a Customer that may have multiple Departments, each one of one or more phone lines. Bills and credit control can be applied in each of the 3 levels mentioned. So, how do we apply this structure in the current model or in a future model that is being planned? Or should we address the situation as a "private" issue that we will need to extend by ourselves? In my view, this situation where a Reseller has a sub-reseller. This sub-reseller have a Customer that may have multiple groups inside of it, each one with different resources sold in a recurring or in a non-recurring base are a frequent scenario and maybe is being planned by you guys. 
Thanks for your attention, 
Daniel
